Repository flatcar/coreos-overlay, pull requests merged in 2019-10, with the labels that each got.

#90 revert perl to 5.26.1
  profiles/coreos/base/package.accept_keywords
  profiles/coreos/base/package.mask
  profiles/coreos/base/package.unmask
  profiles/coreos/targets/generic/package.mask
  profiles/coreos/targets/sdk/package.accept_keywords
  profiles/coreos/targets/sdk/package.mask
  profiles/coreos/targets/sdk/package.unmask
Labels: edge

#89 sys-apps/systemd: bump systemd v242 to fix wireguard
  sys-apps/systemd/systemd-242-r2.ebuild
  sys-apps/systemd/systemd-9999.ebuild
Labels: bug

#87 bump cri-o to 1.15.2
  app-emulation/cri-o/Manifest
  app-emulation/cri-o/cri-o-1.15.2.ebuild
Labels: edge

#91 app-emulation/cri-o: fix path prefix in crio-wipe.service
  app-emulation/cri-o/cri-o-1.15.2.ebuild
Labels: bug, edge

#92 app-emulation/cri-tools: bump cri-tools to 1.16.1
  app-emulation/cri-tools/Manifest
  app-emulation/cri-tools/cri-tools-1.16.1.ebuild
Labels: edge

#93 Fix Go, coreos-firmware, use flags
  coreos-base/hard-host-depends/hard-host-depends-0.0.1-r194.ebuild
  coreos-base/hard-host-depends/hard-host-depends-0.0.1.ebuild
  profiles/coreos/base/package.use
  profiles/coreos/targets/generic/package.use
  sys-kernel/coreos-firmware/Manifest
  sys-kernel/coreos-firmware/coreos-firmware-20190815.ebuild
Labels: edge

#94 app-emulation: bump docker-runc to 1.0.0_rc9
  app-emulation/containerd/containerd-9999.ebuild
  app-emulation/docker-runc/Manifest
  app-emulation/docker-runc/docker-runc-1.0.0_rc9.ebuild
  app-emulation/docker/docker-9999.ebuild
  app-torcx/docker/docker-19.03.ebuild
  metadata/md5-cache/app-emulation/containerd-0.2.6
  metadata/md5-cache/app-emulation/containerd-9999
  metadata/md5-cache/app-emulation/docker-19.03.2
  metadata/md5-cache/app-emulation/docker-9999
  metadata/md5-cache/app-emulation/docker-runc-1.0.0_rc9
  metadata/md5-cache/app-torcx/docker-19.03
Labels: edge

#96 dev-lang/go: bump Go to 1.12.12 and 1.13.3
  app-emulation/containerd/containerd-9999.ebuild
  app-emulation/docker-proxy/docker-proxy-9999.ebuild
  app-emulation/docker-runc/docker-runc-1.0.0_rc9.ebuild
  app-emulation/docker/docker-9999.ebuild
  app-emulation/rkt/rkt-9999.ebuild
  coreos-base/hard-host-depends/hard-host-depends-0.0.1.ebuild
  dev-lang/go/Manifest
  dev-lang/go/go-1.12.12.ebuild
  dev-lang/go/go-1.13.3.ebuild
  eclass/coreos-go-depend.eclass
  eclass/coreos-go.eclass
  metadata/md5-cache/app-admin/locksmith-0.6.2
  metadata/md5-cache/app-admin/locksmith-9999
  metadata/md5-cache/app-admin/mayday-1.0.0
  metadata/md5-cache/app-admin/mayday-9999
  metadata/md5-cache/app-admin/sdnotify-proxy-0.1.0-r2
  metadata/md5-cache/app-admin/sdnotify-proxy-9999
  metadata/md5-cache/app-admin/updateservicectl-2.1.0
  metadata/md5-cache/app-admin/updateservicectl-9999
  metadata/md5-cache/app-arch/torcx-0.2.0-r1
  metadata/md5-cache/app-arch/torcx-9999
  metadata/md5-cache/app-crypt/go-tspi-0.1-r4
  metadata/md5-cache/app-crypt/go-tspi-9999
  metadata/md5-cache/app-emulation/acbuild-0.4.0
  metadata/md5-cache/app-emulation/acbuild-9999
  metadata/md5-cache/app-emulation/actool-0.8.11
  metadata/md5-cache/app-emulation/actool-9999
  metadata/md5-cache/app-emulation/rkt-1.30.0-r1
  metadata/md5-cache/app-emulation/rkt-9999
  metadata/md5-cache/coreos-base/coreos-cloudinit-1.14.0
  metadata/md5-cache/coreos-base/coreos-cloudinit-9999
  metadata/md5-cache/coreos-base/hard-host-depends-0.0.1
  metadata/md5-cache/coreos-base/hard-host-depends-0.0.1-r193
  metadata/md5-cache/coreos-base/nova-agent-watcher-0.0.7-r1
  metadata/md5-cache/coreos-base/nova-agent-watcher-9999
  metadata/md5-cache/coreos-devel/mantle-0.13.0
  metadata/md5-cache/coreos-devel/mantle-9999
  metadata/md5-cache/dev-db/etcdctl-3.3.17
  metadata/md5-cache/sys-apps/ignition-0.33.0-r1
  metadata/md5-cache/sys-apps/ignition-9999
Labels: edge

#97 sys-apps/systemd: update CROS_WORKON_COMMIT to v242-flatcar-edge
  sys-apps/systemd/systemd-242-r3.ebuild
  sys-apps/systemd/systemd-9999.ebuild
Labels: edge

#98 sys-kernel: bump kernel to 5.3.7
  sys-kernel/coreos-kernel/coreos-kernel-5.3.7.ebuild
  sys-kernel/coreos-modules/coreos-modules-5.3.7.ebuild
  sys-kernel/coreos-sources/Manifest
  sys-kernel/coreos-sources/coreos-sources-5.3.7.ebuild
Labels: edge

#99 app-emulation/docker-runc: fix wrong hash for runc 1.0.0-rc9
  app-emulation/docker-runc/Manifest
  metadata/md5-cache/app-emulation/docker-runc-1.0.0_rc9
Labels: edge

#101 Fix CROS_WORKON_COMMIT values for multiple repos
  app-admin/locksmith/locksmith-0.6.2-r1.ebuild
  app-admin/locksmith/locksmith-9999.ebuild
  app-admin/mayday/mayday-1.0.0-r1.ebuild
  app-admin/mayday/mayday-9999.ebuild
  app-admin/sdnotify-proxy/sdnotify-proxy-0.1.0-r3.ebuild
  app-admin/sdnotify-proxy/sdnotify-proxy-9999.ebuild
  app-arch/torcx/torcx-0.2.0-r2.ebuild
  app-arch/torcx/torcx-9999.ebuild
  coreos-base/afterburn/Manifest
  coreos-base/afterburn/afterburn-4.0.0-r1.ebuild
  coreos-base/afterburn/afterburn-9999.ebuild
  coreos-base/coreos-cloudinit/coreos-cloudinit-1.14.0-r1.ebuild
  coreos-base/coreos-cloudinit/coreos-cloudinit-9999.ebuild
  coreos-base/cros-devutils/cros-devutils-0.0.1-r534.ebuild
  coreos-base/cros-devutils/cros-devutils-9999.ebuild
  coreos-base/gmerge/gmerge-0.0.1-r579.ebuild
  coreos-base/gmerge/gmerge-9999.ebuild
  coreos-base/update-ssh-keys/Manifest
  coreos-base/update-ssh-keys/update-ssh-keys-0.3.0-r2.ebuild
  coreos-base/update-ssh-keys/update-ssh-keys-9999.ebuild
  coreos-devel/mantle/mantle-0.13.0-r1.ebuild
  coreos-devel/mantle/mantle-9999.ebuild
  sys-apps/ignition/ignition-0.33.0-r2.ebuild
  sys-apps/ignition/ignition-9999.ebuild
  sys-kernel/bootengine/bootengine-0.0.38-r1.ebuild
  sys-kernel/bootengine/bootengine-9999.ebuild
Labels: bug

#102 Bump docker to 19.03.4, containerd to 1.3.0
  app-emulation/containerd/Manifest
  app-emulation/containerd/containerd-1.3.0.ebuild
  app-emulation/docker/Manifest
  app-emulation/docker/docker-19.03.4.ebuild
  app-emulation/docker/docker-9999.ebuild
  app-torcx/docker/docker-19.03.ebuild
  metadata/md5-cache/app-emulation/containerd-1.3.0
  metadata/md5-cache/app-emulation/containerd-9999
  metadata/md5-cache/app-emulation/docker-19.03.4
  metadata/md5-cache/app-emulation/docker-9999
  metadata/md5-cache/app-emulation/docker-proxy-0.8.0_p20180709
  metadata/md5-cache/app-emulation/docker-proxy-9999
  metadata/md5-cache/app-emulation/docker-runc-1.0.0_rc9
  metadata/md5-cache/app-torcx/docker-19.03
  metadata/md5-cache/coreos-base/hard-host-depends-0.0.1
  metadata/md5-cache/coreos-base/hard-host-depends-0.0.1-r193
Labels: edge

#103 kubelet-wrapper: replace rkt with docker for Edge
  app-admin/etcd-wrapper/etcd-wrapper-3.3.17.ebuild
  app-admin/etcd-wrapper/files/etcd-member.service
  app-admin/etcd-wrapper/files/etcd-wrapper
  app-admin/flannel-wrapper/files/flannel-docker-opts.service
  app-admin/flannel-wrapper/files/flannel-wrapper
  app-admin/flannel-wrapper/files/flanneld.service
  app-admin/flannel-wrapper/flannel-wrapper-0.11.0-r1.ebuild
  app-admin/kubelet-wrapper/files/kubelet-wrapper
  app-admin/kubelet-wrapper/kubelet-wrapper-0.0.4-r1.ebuild
  app-admin/toolbox/toolbox-9999.ebuild
  coreos-base/oem-gce/files/units/oem-gce.service
  coreos-base/oem-gce/oem-gce-20180823-r3.ebuild
Labels: edge

#104 app-arch/torcx: bump torcx to fix Setxattr error issue
  app-arch/torcx/torcx-0.2.0-r3.ebuild
  app-arch/torcx/torcx-9999.ebuild
Labels: bug, edge
