Repository flatcar/coreos-overlay, pull requests merged in 2020-07, with the labels that each got.

#450 sys-kernel: enable kernel config CONFIG_IKHEADERS
  sys-kernel/coreos-modules/files/commonconfig-5.4
Labels: alpha, beta, edge, enhancement

#459 .github: replace COMMIT_ID in runc ebuilds
  .github/workflows/runc-apply-patch.sh
  .github/workflows/runc-releases-alpha.yml
  .github/workflows/runc-releases-edge.yml
Labels: bug, github-actions

#462 sys-apps/ignition: fix package name to fetch
  sys-apps/ignition/ignition-0.34.0-r3.ebuild
  sys-apps/ignition/ignition-9999.ebuild
Labels: alpha, beta, edge, stable

#465 Bump app-admin/etcd-wrapper to 3.3.22
  app-admin/etcd-wrapper/etcd-wrapper-3.3.22.ebuild
Labels: alpha, edge

#381 app-crypt/gnupg: add patches for accepting without UIDs for alpha
  app-crypt/gnupg/Manifest
  app-crypt/gnupg/files/gnupg-2.1.20-gpgscm-Use-shorter-socket-path-lengts-to-improve-tes.patch
  app-crypt/gnupg/files/gnupg-accept-subkeys-with-a-good-revocation-but-no-self-sig.patch
  app-crypt/gnupg/files/gnupg-allow-import-of-previously-known-keys-even-without-UI.patch
  app-crypt/gnupg/gnupg-2.2.20.ebuild
  app-crypt/gnupg/metadata.xml
  profiles/coreos/base/package.accept_keywords
Labels: alpha

#382 app-crypt/gnupg: add patches for accepting without UIDs for edge
  app-crypt/gnupg/Manifest
  app-crypt/gnupg/files/gnupg-2.1.20-gpgscm-Use-shorter-socket-path-lengts-to-improve-tes.patch
  app-crypt/gnupg/files/gnupg-accept-subkeys-with-a-good-revocation-but-no-self-sig.patch
  app-crypt/gnupg/files/gnupg-allow-import-of-previously-known-keys-even-without-UI.patch
  app-crypt/gnupg/gnupg-2.2.20.ebuild
  app-crypt/gnupg/metadata.xml
  profiles/coreos/base/package.accept_keywords
Labels: edge

#466 Bump flannel-wrapper to 0.12.0
  app-admin/flannel-wrapper/flannel-wrapper-0.12.0.ebuild
Labels: alpha, edge

#402 sys-apps/bpftool: update to 5.7 to adjust it to Kernel 5.7 for edge
  sys-apps/bpftool/Manifest
  sys-apps/bpftool/bpftool-5.7.ebuild
  sys-apps/bpftool/bpftool-9999.ebuild
Labels: edge

#431 sys-libs/glibc: update glibc to 2.30-r8 for alpha
  sys-libs/glibc/Manifest
  sys-libs/glibc/files/2.25/glibc-2.25-gshadow-handle-erange.patch
  sys-libs/glibc/files/host.conf-1
  sys-libs/glibc/files/nscd-1
  sys-libs/glibc/files/nscd.service
  sys-libs/glibc/files/nscd.tmpfilesd
  sys-libs/glibc/glibc-2.30-r8.ebuild
  sys-libs/glibc/metadata.xml
Labels: alpha, enhancement

#490 coreos-base/coreos-init: revision bump
  coreos-base/coreos-init/coreos-init-0.0.1-r166.ebuild
Labels: alpha, edge
