Repository flatcar/coreos-overlay, pull requests merged in 2020-08, with the labels that each got.

#511 sys-apps/systemd: Update systemd to v245.7
  sys-apps/systemd/systemd-245-r2.ebuild
  sys-apps/systemd/systemd-9999.ebuild
Labels: alpha, edge

#528 add qedf, qedi, qla4xxx modules
  sys-kernel/coreos-modules/files/commonconfig-5.4
Labels: main

#529 app-admin/etcd-wrapper: Bump to 3.3.23
  app-admin/etcd-wrapper/etcd-wrapper-3.3.23.ebuild
Labels: alpha

#530 app-admin/etcd-wrapper: Bump to 3.3.23
  app-admin/etcd-wrapper/etcd-wrapper-3.3.23.ebuild
Labels: flatcar-2513

#535 app-admin/etcd-wrapper: Bump to 3.3.24
  app-admin/etcd-wrapper/etcd-wrapper-3.3.24.ebuild
Labels: alpha, flatcar-2512, flatcar-2513

#536 app-admin/etcd-wrapper: Adjust data dir permissions, Bump to 3.3.24
  app-admin/etcd-wrapper/etcd-wrapper-3.3.24.ebuild
  app-admin/etcd-wrapper/files/etcd-wrapper.conf
Labels: flatcar-2512, flatcar-2513

#551 Bump etcdctl and etcd-wrapper to 3.3.25
  app-admin/etcd-wrapper/etcd-wrapper-3.3.25.ebuild
  dev-db/etcdctl/Manifest
  dev-db/etcdctl/etcdctl-3.3.25.ebuild
Labels: alpha, flatcar-2605

#552 app-emulation/open-vm-tools: update to 11.1.5
  app-emulation/open-vm-tools/Manifest
  app-emulation/open-vm-tools/files/open-vm-tools-11.1.5-0001-configure-Add-options-for-fuse-hgfs-and-udev.patch
  app-emulation/open-vm-tools/open-vm-tools-11.1.5.ebuild
  coreos-base/oem-vmware/oem-vmware-11.1.5.ebuild
Labels: alpha

#554 sys-kernel: allow fips mode to be enabled
  sys-kernel/coreos-modules/files/commonconfig-5.4
Labels: enhancement
