Repository flatcar/coreos-overlay, pull requests merged in 2020-09, with the labels that each got.

#556 dev-lang/go: Update the default Go version to 1.15
  .github/workflows/go-releases-main.yml
  app-emulation/containerd/containerd-9999.ebuild
  app-emulation/docker-proxy/docker-proxy-9999.ebuild
  app-emulation/docker-runc/docker-runc-1.0.0_rc90.ebuild
  app-emulation/docker/docker-9999.ebuild
  dev-lang/go/Manifest
  dev-lang/go/go-1.15.ebuild
  eclass/coreos-go-depend.eclass
  eclass/coreos-go.eclass
Labels: alpha

#561 coreos-base: Allow installation to multipath target
  coreos-base/coreos-init/coreos-init-0.0.1-r168.ebuild
  coreos-base/coreos-init/coreos-init-9999.ebuild
Labels: alpha

#571 .github: fix regexp to get correct semver from Go ebuilds
  .github/workflows/go-apply-patch.sh
Labels: bug, github-actions

#575 .github: improve body text of PR for dev-lang/rust
  .github/workflows/rust-apply-patch.sh
  .github/workflows/rust-release-main.yml
Labels: enhancement, github-actions

#574 dev-lang: Upgrade Go 1.15 to 1.15.2
  dev-lang/go/Manifest
  dev-lang/go/go-1.15.2.ebuild
Labels: alpha

#553 sys-kernel: make lockdown available
  sys-kernel/coreos-modules/files/commonconfig-5.8
Labels: enhancement

#495 app-emulation/qemu: Upgrade qemu to 5.0.0
  app-emulation/qemu/qemu-5.0.0.ebuild
Labels: alpha

#590 profile: adjust profiles for jq, rsync
  profiles/coreos/base/package.accept_keywords
  profiles/coreos/base/package.use
Labels: main

#600 dev-db/sqlite: update to 3.32.3 to keep non-full archive
  dev-db/sqlite/Manifest
  dev-db/sqlite/README.md
  dev-db/sqlite/files/sqlite-3.32.1-full_archive-build_1.patch
  dev-db/sqlite/files/sqlite-3.32.1-full_archive-build_2.patch
  dev-db/sqlite/files/sqlite-3.32.3-full_archive-backports_1.patch
  dev-db/sqlite/files/sqlite-3.32.3-full_archive-backports_2.patch
  dev-db/sqlite/files/sqlite-3.32.3-full_archive-backports_3.patch
  dev-db/sqlite/files/sqlite-3.32.3-nonfull_archive-backports_1.patch
  dev-db/sqlite/files/sqlite-3.32.3-nonfull_archive-backports_2.patch
  dev-db/sqlite/files/sqlite-3.32.3-nonfull_archive-backports_3.patch
  dev-db/sqlite/files/sqlite-3.32.3-nonfull_archive-build.patch
  dev-db/sqlite/metadata.xml
  dev-db/sqlite/sqlite-3.32.3-r1.ebuild
Labels: main

#598 profiles: adjust to clean up serf, apr-util
  profiles/coreos/arm64/package.accept_keywords
  profiles/coreos/base/package.use
Labels: main

#620 Adjust the `srctree` based on the presence of KBUILD_OUTPUT
  sys-kernel/coreos-sources/files/5.8/z0001-kbuild-derive-relative-path-for-srctree-from-CURDIR.patch
Labels: flatcar-2605, flatcar-2632, flatcar-2643

#611 coreos-base/hard-host-depends: add dev-lang/tcl
  coreos-base/hard-host-depends/hard-host-depends-0.0.1-r194.ebuild
  coreos-base/hard-host-depends/hard-host-depends-0.0.1.ebuild
Labels: main
