Repository flatcar/coreos-overlay, pull requests merged in 2020-11, with the labels that each got.

#659 Update systemd (sync, use gentoo workflow, add missing patches)
  sys-apps/systemd/Manifest
  sys-apps/systemd/files/0001-sysctl.d-50-default.conf-remove-.all-source-route-se.patch
  sys-apps/systemd/files/0002-sysctl.d-50-default-better-comments-re-activate-prom.patch
  sys-apps/systemd/files/0003-sysctl.d-50-default.conf-re-activate-default-accept_.patch
  sys-apps/systemd/files/0004-wait-online-set-any-by-default.patch
  sys-apps/systemd/files/0005-networkd-default-to-kernel-IPForwarding-setting.patch
  sys-apps/systemd/files/0006-needs-update-don-t-require-strictly-newer-usr.patch
  sys-apps/systemd/files/0007-core-use-max-for-DefaultTasksMax.patch
  sys-apps/systemd/files/0008-systemd-Disable-SELinux-permissions-checks.patch
  sys-apps/systemd/systemd-246.6.ebuild
  sys-apps/systemd/systemd-9999.ebuild
Labels: main

#669 dev-libs/dbus-glib: update to 0.110, fix cross compile build error
  dev-libs/dbus-glib/ChangeLog
  dev-libs/dbus-glib/ChangeLog-2015
  dev-libs/dbus-glib/Manifest
  dev-libs/dbus-glib/dbus-glib-0.104.ebuild
  dev-libs/dbus-glib/dbus-glib-0.106-r1.ebuild
  dev-libs/dbus-glib/dbus-glib-0.110-r1.ebuild
Labels: alpha, main

#638 sys-kernel/coreos-modules: enable PSI (Pressure Stall Information)
  sys-kernel/coreos-modules/files/commonconfig-5.9
Labels: enhancement, main

#682 sys-block/open-iscsi: Add the version 2.1.2
  sys-block/open-iscsi/Manifest
  sys-block/open-iscsi/files/iscsid-conf.d
  sys-block/open-iscsi/files/iscsid-init.d
  sys-block/open-iscsi/files/open-iscsi-2.1.1-Makefiles.patch
  sys-block/open-iscsi/open-iscsi-2.1.2.ebuild
Labels: alpha

#671 sys-apps/shadow: update to 4.8-r5, apply Flatcar changes
  sys-apps/shadow/Manifest
  sys-apps/shadow/files/pam.d-include/chpasswd
  sys-apps/shadow/files/pam.d-include/shadow-r1
  sys-apps/shadow/files/shadow-4.8-revert-bin-merge.patch
  sys-apps/shadow/metadata.xml
  sys-apps/shadow/shadow-4.8-r5.ebuild
Labels: alpha, main

#675 profiles: enable gssapi for bind-tools in SDK
  profiles/coreos/targets/sdk/package.use
Labels: bug, main

#681 app-emulation/open-vm-tools: update to 11.2.0
  app-emulation/open-vm-tools/Manifest
  app-emulation/open-vm-tools/files/open-vm-tools-11.2.0-0001-configure-Add-options-for-fuse-hgfs-and-udev.patch
  app-emulation/open-vm-tools/open-vm-tools-11.2.0.ebuild
  coreos-base/oem-vmware/oem-vmware-11.2.0.ebuild
Labels: alpha, main

#685 .github: fix mantle URL for downloading cork
  .github/workflows/setup-flatcar-sdk.sh
Labels: bug, github-actions

#686 eclass: remove also other optimization flags with -Wl,-O*
  eclass/coreos-go-utils.eclass
Labels: alpha, beta, bug, main

#691 sys-kernel: enable BPF_JIT, POWER_SUPPLY, overlayfs options
  sys-kernel/coreos-modules/files/commonconfig-5.9
Labels: alpha, enhancement, main

#690 profiles: make SDK include dev-util/dwarves
  coreos-devel/sdk-depends/sdk-depends-0.0.1.ebuild
  profiles/coreos/base/package.accept_keywords
  profiles/coreos/base/package.use
Labels: alpha, main

#694 sys-apps/systemd: Point to the latest commit
  sys-apps/systemd/systemd-9999.ebuild
Labels: flatcar-2605, stable

#710 Add the support for GPU on Azure
  coreos-base/oem-azure-pro/files/base/README
  coreos-base/oem-azure-pro/files/base/base.ign
  coreos-base/oem-azure-pro/files/base/default.ign
  coreos-base/oem-azure-pro/files/grub.cfg
  coreos-base/oem-azure-pro/files/oem-release
  coreos-base/oem-azure-pro/files/units/waagent.service
  coreos-base/oem-azure-pro/metadata.xml
  coreos-base/oem-azure-pro/oem-azure-pro-2.2.46.ebuild
  coreos-devel/board-packages/board-packages-0.0.1.ebuild
  x11-drivers/nvidia-drivers/files/bin/install-nvidia
  x11-drivers/nvidia-drivers/files/bin/setup-nvidia
  x11-drivers/nvidia-drivers/files/units/nvidia.service
  x11-drivers/nvidia-drivers/nvidia-drivers-450.80.02.ebuild
Labels: flatcar-2643
