Repository flatcar/coreos-overlay, pull requests merged in 2020-04, with the labels that each got.

#255 .github: update Kernel to 5.6 for Edge
  .github/workflows/kernel-releases-edge.yml
Labels: github-actions

#259 app-emulation/open-vm-tools: update to 11.0.5 for alpha
  app-emulation/open-vm-tools/Manifest
  app-emulation/open-vm-tools/files/open-vm-tools-11.0.5-0001-configure-Add-options-for-fuse-hgfs-and-udev.patch
  app-emulation/open-vm-tools/open-vm-tools-11.0.5.ebuild
  coreos-base/oem-vmware/oem-vmware-11.0.5.ebuild
Labels: alpha

#260 app-emulation/open-vm-tools: update to 11.0.5 for edge
  app-emulation/open-vm-tools/Manifest
  app-emulation/open-vm-tools/files/open-vm-tools-11.0.5-0001-configure-Add-options-for-fuse-hgfs-and-udev.patch
  app-emulation/open-vm-tools/open-vm-tools-11.0.5.ebuild
  coreos-base/oem-vmware/oem-vmware-11.0.5.ebuild
Labels: edge

#258 .github: fix metadata generation for Kernel and Go
  .github/workflows/go-apply-patch.sh
  .github/workflows/kernel-apply-patch.sh
Labels: bug, github-actions

#263 profiles: accept keywords ~arm64 for openssh 8.1 for alpha
  profiles/coreos/base/package.accept_keywords
Labels: alpha, bug

#264 profiles: accept keywords ~arm64 for openssh 8.1 for edge
  profiles/coreos/base/package.accept_keywords
Labels: bug, edge

#266 coreos-base/gmerge: do not check out coreos branches
  coreos-base/gmerge/gmerge-0.0.1-r582.ebuild
  coreos-base/gmerge/gmerge-9999.ebuild
Labels: alpha, beta, bug, edge, stable

#265 .github: check out correct base branches before applying patches
  .github/workflows/docker-apply-patch.sh
  .github/workflows/go-apply-patch.sh
  .github/workflows/kernel-apply-patch.sh
  .github/workflows/runc-apply-patch.sh
Labels: bug, github-actions

#270 coreos-base/gmerge: do not touch commit if it is of NoneType
  coreos-base/gmerge/gmerge-0.0.1-r583.ebuild
  coreos-base/gmerge/gmerge-9999.ebuild
Labels: alpha, beta, bug, edge, stable

#269 .github: use correct make.conf when setting up Flatcar SDK
  .github/workflows/setup-flatcar-sdk.sh
Labels: bug, github-actions

#216 .github: schedule daily Github actions for Rust
  .github/workflows/common.sh
  .github/workflows/docker-apply-patch.sh
  .github/workflows/go-apply-patch.sh
  .github/workflows/kernel-apply-patch.sh
  .github/workflows/runc-apply-patch.sh
  .github/workflows/rust-apply-patch.sh
  .github/workflows/rust-release-alpha.yml
  .github/workflows/rust-release-edge.yml
Labels: github-actions

#252 app-emulation/qemu: update to 4.2.0-r2 for alpha
  app-emulation/qemu/Manifest
  app-emulation/qemu/files/0001-block-fix-vpc-max_table_entries-computation.patch
  app-emulation/qemu/files/qemu-4.0.0-fix_infiniband_include.patch
  app-emulation/qemu/files/qemu-4.0.0-linux-headers-5.2.patch
  app-emulation/qemu/files/qemu-4.0.0-mkdir_systemtap.patch
  app-emulation/qemu/files/qemu-4.0.0-pc-q35-4.0.patch
  app-emulation/qemu/files/qemu-4.0.0-xkbcommon.patch
  app-emulation/qemu/files/qemu-4.2.0-cflags.patch
  app-emulation/qemu/metadata.xml
  app-emulation/qemu/qemu-4.2.0-r2.ebuild
  profiles/coreos/base/package.accept_keywords
  profiles/coreos/base/package.use
Labels: alpha

#253 app-emulation/qemu: update to 4.2.0-r2 for edge
  app-emulation/qemu/Manifest
  app-emulation/qemu/files/0001-block-fix-vpc-max_table_entries-computation.patch
  app-emulation/qemu/files/qemu-4.0.0-fix_infiniband_include.patch
  app-emulation/qemu/files/qemu-4.0.0-linux-headers-5.2.patch
  app-emulation/qemu/files/qemu-4.0.0-mkdir_systemtap.patch
  app-emulation/qemu/files/qemu-4.0.0-pc-q35-4.0.patch
  app-emulation/qemu/files/qemu-4.0.0-xkbcommon.patch
  app-emulation/qemu/files/qemu-4.2.0-cflags.patch
  app-emulation/qemu/metadata.xml
  app-emulation/qemu/qemu-4.2.0-r2.ebuild
  profiles/coreos/base/package.accept_keywords
  profiles/coreos/base/package.use
Labels: edge

#291 .github: detect kernel version correctly
  .github/workflows/kernel-apply-patch.sh
Labels: github-actions

#289 profiles: enable selinux for docker-runc for alpha
  app-emulation/docker-runc/docker-runc-1.0.0_rc10.ebuild
  app-emulation/docker-runc/files/0001-temporarily-disable-selinux.GetEnabled-error-checks.patch
  profiles/coreos/amd64/generic/package.use
  profiles/coreos/arm64/package.use
Labels: alpha

#290 profiles: enable selinux for docker-runc for edge
  app-emulation/docker-runc/docker-runc-1.0.0_rc10.ebuild
  app-emulation/docker-runc/files/0001-temporarily-disable-selinux.GetEnabled-error-checks.patch
  profiles/coreos/amd64/generic/package.use
  profiles/coreos/arm64/package.use
Labels: edge

#297 net-firewall/conntrack-tools: Add the package to coreos
  coreos-base/coreos/coreos-0.0.1-r294.ebuild
  coreos-base/coreos/coreos-0.0.1.ebuild
  metadata/md5-cache/coreos-base/coreos-0.0.1-r293
  metadata/md5-cache/coreos-base/coreos-0.0.1-r294
  profiles/coreos/arm64/package.accept_keywords
Labels: alpha, beta, edge, stable

#303 .github: update Kernel version to 5.4 for Alpha
  .github/workflows/kernel-releases-alpha.yml
Labels: github-actions

#306 net-firewall/conntrack-tools: Add the new package to alpha
  coreos-base/coreos/coreos-0.0.1-r294.ebuild
  coreos-base/coreos/coreos-0.0.1.ebuild
  metadata/md5-cache/app-emulation/docker-runc-1.0.0_rc10
  metadata/md5-cache/app-emulation/qemu-4.0.0-r3
  metadata/md5-cache/app-emulation/qemu-4.2.0-r2
  metadata/md5-cache/coreos-base/coreos-0.0.1-r293
  metadata/md5-cache/coreos-base/coreos-0.0.1-r294
  metadata/md5-cache/sys-apps/ignition-0.34.0-r2
  metadata/md5-cache/sys-apps/ignition-9999
  profiles/coreos/arm64/package.accept_keywords
Labels: alpha

#304 net-firewall/conntrack-tools: Add the package to edge
  coreos-base/coreos/coreos-0.0.1-r294.ebuild
  coreos-base/coreos/coreos-0.0.1.ebuild
  metadata/md5-cache/coreos-base/coreos-0.0.1-r293
  metadata/md5-cache/coreos-base/coreos-0.0.1-r294
  profiles/coreos/arm64/package.accept_keywords
Labels: edge

#309 sys-devel/gdb: update to 9.1 for alpha
  metadata/md5-cache/sys-devel/gdb-7.10.1
  metadata/md5-cache/sys-devel/gdb-7.12.1
  metadata/md5-cache/sys-devel/gdb-7.9.1
  metadata/md5-cache/sys-devel/gdb-8.1-r1
  metadata/md5-cache/sys-devel/gdb-8.1-r2
  metadata/md5-cache/sys-devel/gdb-8.1.1
  metadata/md5-cache/sys-devel/gdb-8.2
  metadata/md5-cache/sys-devel/gdb-9.1-r1
  metadata/md5-cache/sys-devel/gdb-9999
  sys-devel/gdb/Manifest
  sys-devel/gdb/files/gdb-7.12.1-ia64-include.patch
  sys-devel/gdb/files/gdb-8.3.1-verbose-build.patch
  sys-devel/gdb/gdb-7.10.1.ebuild
  sys-devel/gdb/gdb-7.12.1.ebuild
  sys-devel/gdb/gdb-7.9.1.ebuild
  sys-devel/gdb/gdb-8.1-r2.ebuild
  sys-devel/gdb/gdb-8.1.1.ebuild
  sys-devel/gdb/gdb-8.2.ebuild
  sys-devel/gdb/gdb-9.1-r1.ebuild
  sys-devel/gdb/gdb-9999.ebuild
  sys-devel/gdb/metadata.xml
Labels: alpha

#310 sys-devel/gdb: update to 9.1 for edge
  metadata/md5-cache/sys-devel/gdb-7.10.1
  metadata/md5-cache/sys-devel/gdb-7.12.1
  metadata/md5-cache/sys-devel/gdb-7.9.1
  metadata/md5-cache/sys-devel/gdb-8.1-r1
  metadata/md5-cache/sys-devel/gdb-8.1-r2
  metadata/md5-cache/sys-devel/gdb-8.1.1
  metadata/md5-cache/sys-devel/gdb-8.2
  metadata/md5-cache/sys-devel/gdb-9.1-r1
  metadata/md5-cache/sys-devel/gdb-9999
  sys-devel/gdb/Manifest
  sys-devel/gdb/files/gdb-7.12.1-ia64-include.patch
  sys-devel/gdb/files/gdb-8.3.1-verbose-build.patch
  sys-devel/gdb/gdb-7.10.1.ebuild
  sys-devel/gdb/gdb-7.12.1.ebuild
  sys-devel/gdb/gdb-7.9.1.ebuild
  sys-devel/gdb/gdb-8.1-r2.ebuild
  sys-devel/gdb/gdb-8.1.1.ebuild
  sys-devel/gdb/gdb-8.2.ebuild
  sys-devel/gdb/gdb-9.1-r1.ebuild
  sys-devel/gdb/gdb-9999.ebuild
  sys-devel/gdb/metadata.xml
Labels: edge

#318 profile: set python 3.6 single target for cross builds for alpha
  profiles/coreos/targets/sdk/package.use
Labels: alpha, bug

#319 profile: set python 3.6 single target for cross builds for edge
  profiles/coreos/targets/sdk/package.use
Labels: bug, edge

#317 .github: detect latest cork version during SDK setup
  .github/workflows/containerd-releases-alpha.yml
  .github/workflows/containerd-releases-edge.yml
  .github/workflows/docker-releases-alpha.yml
  .github/workflows/docker-releases-edge.yml
  .github/workflows/go-releases-alpha.yml
  .github/workflows/go-releases-edge.yml
  .github/workflows/kernel-releases-alpha.yml
  .github/workflows/kernel-releases-beta.yml
  .github/workflows/kernel-releases-edge.yml
  .github/workflows/kernel-releases-stable.yml
  .github/workflows/runc-releases-alpha.yml
  .github/workflows/runc-releases-edge.yml
  .github/workflows/rust-release-alpha.yml
  .github/workflows/rust-release-edge.yml
  .github/workflows/setup-flatcar-sdk.sh
Labels: github-actions

#323 profiles: bump edk2-ovmf to 201905 for alpha
  profiles/coreos/base/package.accept_keywords
Labels: alpha, bug

#324 profiles: bump edk2-ovmf to 201905 for edge
  profiles/coreos/base/package.accept_keywords
Labels: bug, edge

#325 profiles: enable fero-client for alpha
  profiles/coreos/base/package.accept_keywords
Labels: alpha, bug

#326 profiles: enable fero-client for edge
  profiles/coreos/base/package.accept_keywords
Labels: bug, edge
