Repository flatcar/coreos-overlay, pull requests merged in 2020-06, with the labels that each got.

#401 .github: fix version format in docker-runc
  .github/workflows/runc-apply-patch.sh
Labels: bug, github-actions

#411 profiles: enable bind-tools again for ARM for alpha
  profiles/coreos/amd64/generic/package.use
  profiles/coreos/arm64/package.provided
  profiles/coreos/arm64/package.use
  profiles/coreos/base/package.use
  sys-auth/sssd/sssd-1.13.1-r7.ebuild
Labels: alpha, bug

#412 profiles: enable bind-tools again for ARM for edge
  profiles/coreos/amd64/generic/package.use
  profiles/coreos/arm64/package.provided
  profiles/coreos/arm64/package.use
  profiles/coreos/base/package.use
  sys-auth/sssd/sssd-1.13.1-r7.ebuild
Labels: bug, edge

#400 sys-apps/systemd: Manually enable the getty service
  sys-apps/systemd/systemd-9999.ebuild
Labels: alpha, edge

#422 sys-firmware/intel-microcode: update to 20200609
  sys-firmware/intel-microcode/Manifest
  sys-firmware/intel-microcode/intel-microcode-20200609_p20200601-r1.ebuild
Labels: beta, stable

#421 sys-firmware/intel-microcode: update to 20200609
  sys-firmware/intel-microcode/Manifest
  sys-firmware/intel-microcode/intel-microcode-20200609_p20200601-r1.ebuild
Labels: alpha, edge

#432 .github: update rust versions also in profiles
  .github/workflows/rust-apply-patch.sh
Labels: bug, github-actions

#444 profiles: force to use ssl USE flag for wget
  profiles/coreos/arm64/package.use.force
  profiles/coreos/base/package.use.force
Labels: alpha, beta, bug, edge, stable

#433 sys-kernel/coreos-sources: Update kernel from 5.6 to 5.7
  sys-kernel/coreos-kernel/coreos-kernel-5.7.6.ebuild
  sys-kernel/coreos-modules/coreos-modules-5.7.6.ebuild
  sys-kernel/coreos-modules/files/amd64_defconfig-5.7
  sys-kernel/coreos-modules/files/arm64_defconfig-5.7
  sys-kernel/coreos-modules/files/commonconfig-5.7
  sys-kernel/coreos-sources/Manifest
  sys-kernel/coreos-sources/coreos-sources-5.7.6.ebuild
  sys-kernel/coreos-sources/files/5.7/z0001-kbuild-derive-relative-path-for-KBUILD_SRC-from-CURD.patch
  sys-kernel/coreos-sources/files/5.7/z0002-tools-objtool-Makefile-Don-t-fail-on-fallthrough-wit.patch
  sys-kernel/coreos-sources/files/5.7/z0003-net-netfilter-add-nf_conntrack_ipv4-compat-module-fo.patch
Labels: edge

#435 .github/workflows: Update the kernel release edge version to 5.7
  .github/workflows/kernel-releases-edge.yml
Labels: edge

#434 Revert "Merge pull request #290 from flatcar-linux/dongsu/docker-runc…
  app-emulation/docker-runc/docker-runc-1.0.0_rc10.ebuild
  app-emulation/docker-runc/files/0001-temporarily-disable-selinux.GetEnabled-error-checks.patch
  profiles/coreos/amd64/generic/package.use
  profiles/coreos/arm64/package.use
Labels: edge

#396 app-emulation/docker: set go1.13 in DOCKER_BUILDTAGS for alpha
  app-emulation/docker/docker-9999.ebuild
Labels: alpha, bug

#397 app-emulation/docker: set go1.13 in DOCKER_BUILDTAGS for edge
  app-emulation/docker/docker-9999.ebuild
Labels: bug, edge

#447 Revert "profiles: force to use ssl USE flag for wget"
  profiles/coreos/arm64/package.use.force
  profiles/coreos/base/package.use.force
Labels: alpha, beta, bug, edge, stable
