Repository flatcar/coreos-overlay, pull requests merged in 2020-05, with the labels that each got.

#345 sys-kernel/coreos-modules: Add the wireguard module
  coreos-base/coreos/coreos-0.0.1-r296.ebuild
  coreos-base/coreos/coreos-0.0.1.ebuild
  metadata/md5-cache/coreos-base/coreos-0.0.1-r295
  metadata/md5-cache/coreos-base/coreos-init-0.0.1-r165
  metadata/md5-cache/coreos-base/coreos-init-9999
  metadata/md5-cache/sys-kernel/coreos-kernel-5.4.38
  metadata/md5-cache/sys-kernel/coreos-kernel-5.4.38-r1
  metadata/md5-cache/sys-kernel/coreos-modules-5.4.38-r1
  metadata/md5-cache/sys-kernel/coreos-sources-5.4.38-r1
  net-vpn/wireguard-tools/Manifest
  net-vpn/wireguard-tools/metadata.xml
  net-vpn/wireguard-tools/wireguard-tools-1.0.20200319.ebuild
  sys-kernel/coreos-kernel/coreos-kernel-5.4.38-r1.ebuild
  sys-kernel/coreos-modules/coreos-modules-5.4.38-r1.ebuild
  sys-kernel/coreos-sources/coreos-sources-5.4.38-r1.ebuild
  sys-kernel/coreos-sources/files/5.4/z0004-add-wireguard-module.patch
Labels: alpha

#346 net-vpn/wireguard-tools: rename wireguard to wireguard-tools for edge
  coreos-base/coreos/coreos-0.0.1-r295.ebuild
  coreos-base/coreos/coreos-0.0.1.ebuild
  net-vpn/wireguard-tools/Manifest
  net-vpn/wireguard-tools/metadata.xml
  net-vpn/wireguard-tools/wireguard-tools-1.0.20200319.ebuild
  net-vpn/wireguard/Manifest
  net-vpn/wireguard/wireguard-0.0.20191212.ebuild
  net-vpn/wireguard/wireguard-9999.ebuild
Labels: edge

#357 .github: skip branch checkout if it exists
  .github/workflows/common.sh
  .github/workflows/containerd-apply-patch.sh
  .github/workflows/containerd-releases-alpha.yml
  .github/workflows/containerd-releases-edge.yml
  .github/workflows/docker-apply-patch.sh
  .github/workflows/docker-releases-alpha.yml
  .github/workflows/docker-releases-edge.yml
  .github/workflows/go-apply-patch.sh
  .github/workflows/go-releases-alpha.yml
  .github/workflows/go-releases-edge.yml
  .github/workflows/kernel-apply-patch.sh
  .github/workflows/kernel-releases-alpha.yml
  .github/workflows/kernel-releases-beta.yml
  .github/workflows/kernel-releases-edge.yml
  .github/workflows/kernel-releases-stable.yml
  .github/workflows/runc-apply-patch.sh
  .github/workflows/runc-releases-alpha.yml
  .github/workflows/runc-releases-edge.yml
  .github/workflows/rust-apply-patch.sh
  .github/workflows/rust-release-alpha.yml
  .github/workflows/rust-release-edge.yml
Labels: github-actions

#353 sys-apps/seismograph: update to fix rootdev and cgpt
  sys-apps/seismograph/seismograph-2.2.5-r2.ebuild
  sys-apps/seismograph/seismograph-9999.ebuild
Labels: alpha, beta, edge, stable

#356 sys-apps/systemd: Bump to v243 along with needed ebuild changes
  metadata/md5-cache/sys-apps/systemd-243
  metadata/md5-cache/sys-apps/systemd-9999
  sys-apps/systemd/systemd-243.ebuild
  sys-apps/systemd/systemd-9999.ebuild
Labels: alpha

#370 .github: correctly check status of checkout_branches
  .github/workflows/common.sh
  .github/workflows/containerd-apply-patch.sh
  .github/workflows/docker-apply-patch.sh
  .github/workflows/go-apply-patch.sh
  .github/workflows/kernel-apply-patch.sh
  .github/workflows/runc-apply-patch.sh
  .github/workflows/rust-apply-patch.sh
Labels: bug, github-actions

#376 Revert "Merge pull request #289 from flatcar-linux/dongsu/docker-runc-selinux-alpha"
  app-emulation/docker-runc/docker-runc-1.0.0_rc10.ebuild
  app-emulation/docker-runc/files/0001-temporarily-disable-selinux.GetEnabled-error-checks.patch
  profiles/coreos/amd64/generic/package.use
  profiles/coreos/arm64/package.use
Labels: alpha

#363 .github: update Kernel version to 5.4 for beta
  .github/workflows/kernel-releases-beta.yml
Labels: github-actions

#327 dev-util/strace: bump to 5.6 for alpha
  dev-util/strace/Manifest
  dev-util/strace/files/strace-5.4-fix-LTO-CFLAGS-handling.patch
  dev-util/strace/metadata.xml
  dev-util/strace/strace-5.6.ebuild
  metadata/md5-cache/dev-util/strace-5.6
  profiles/coreos/base/package.accept_keywords
Labels: alpha

#328 dev-util/strace: bump to 5.6 for edge
  dev-util/strace/Manifest
  dev-util/strace/files/strace-5.4-fix-LTO-CFLAGS-handling.patch
  dev-util/strace/metadata.xml
  dev-util/strace/strace-5.6.ebuild
  metadata/md5-cache/dev-util/strace-5.6
  profiles/coreos/base/package.accept_keywords
Labels: edge

#383 app-emulation/docker: Fix URLs for docker-ce tarballs for alpha
  app-emulation/docker-runc/docker-runc-1.0.0_rc10.ebuild
  app-emulation/docker/docker-9999.ebuild
  metadata/md5-cache/app-emulation/docker-19.03.8
Labels: alpha, bug

#384 app-emulation/docker: Fix URLs for docker-ce tarballs for edge
  app-emulation/docker-runc/docker-runc-1.0.0_rc10.ebuild
  app-emulation/docker/docker-9999.ebuild
  metadata/md5-cache/app-emulation/docker-19.03.8
Labels: bug, edge
