Repository flatcar/coreos-overlay, pull requests merged in 2020-02, with the labels that each got.

#163 Use rkt again instead of docker in etcd/flannel-wrappers for Edge
  app-admin/etcd-wrapper/etcd-wrapper-3.3.18.ebuild
  app-admin/etcd-wrapper/files/etcd-member.service
  app-admin/etcd-wrapper/files/etcd-wrapper
  app-admin/flannel-wrapper/files/flannel-docker-opts.service
  app-admin/flannel-wrapper/files/flannel-wrapper
  app-admin/flannel-wrapper/files/flanneld.service
  app-admin/flannel-wrapper/flannel-wrapper-0.11.0.ebuild
  app-admin/toolbox/toolbox-9999.ebuild
Labels: bug, edge

#154 app-admin/sudo: bump sudo to 1.8.31 for edge
  app-admin/sudo/Manifest
  app-admin/sudo/sudo-1.8.31.ebuild
  profiles/coreos/arm64/package.accept_keywords
Labels: edge

#164 coreos-devel: make SDK include dev-util/dwarves
  coreos-devel/sdk-depends/sdk-depends-0.0.1-r42.ebuild
  coreos-devel/sdk-depends/sdk-depends-0.0.1.ebuild
  profiles/coreos/base/package.accept_keywords
Labels: edge

#165 sys-kernel: bump kernel to 5.4.16, wireguard to 20200128
  sys-kernel/coreos-kernel/coreos-kernel-5.4.16.ebuild
  sys-kernel/coreos-modules/coreos-modules-5.4.16.ebuild
  sys-kernel/coreos-sources/Manifest
  sys-kernel/coreos-sources/coreos-sources-5.4.16.ebuild
  sys-kernel/coreos-sources/files/5.4/z0004-wireguard.patch
Labels: edge

#169 profiles: enable static-libs for dev-libs/elfutils
  profiles/coreos/targets/generic/package.use
  profiles/coreos/targets/sdk/package.use
Labels: bug, edge

#161 sys-kernel: enable kernel config CONFIG_DEBUG_INFO_BTF for edge
  sys-kernel/coreos-modules/files/commonconfig-5.4
Labels: edge

#174 sys-apps/systemd: bump systemd v242 to address CVE-2020-1712 for edge
  metadata/md5-cache/sys-apps/systemd-242-r4
  metadata/md5-cache/sys-apps/systemd-9999
  sys-apps/systemd/systemd-242-r4.ebuild
  sys-apps/systemd/systemd-9999.ebuild
Labels: edge

#177 *: update CROS_WORKON_COMMIT for backwards compatibility
  coreos-base/afterburn/afterburn-4.0.0-r4.ebuild
  coreos-base/afterburn/afterburn-9999.ebuild
  coreos-base/coreos-init/coreos-init-0.0.1-r165.ebuild
  coreos-base/coreos-init/coreos-init-9999.ebuild
  sys-apps/ignition/ignition-0.34.0-r1.ebuild
  sys-apps/ignition/ignition-9999.ebuild
  sys-kernel/bootengine/bootengine-0.0.38-r2.ebuild
  sys-kernel/bootengine/bootengine-9999.ebuild
Labels: bug

#172 sys-kernel: bump kernel to 4.19.102 for alpha 2411
  metadata/md5-cache/app-admin/locksmith-0.6.2-r1
  metadata/md5-cache/app-admin/locksmith-9999
  metadata/md5-cache/app-admin/mayday-1.0.0-r1
  metadata/md5-cache/app-admin/mayday-9999
  metadata/md5-cache/app-admin/sdnotify-proxy-0.1.0-r3
  metadata/md5-cache/app-admin/sdnotify-proxy-9999
  metadata/md5-cache/app-admin/toolbox-0.0.0-r13
  metadata/md5-cache/app-admin/toolbox-9999
  metadata/md5-cache/app-admin/updateservicectl-2.1.0
  metadata/md5-cache/app-admin/updateservicectl-9999
  metadata/md5-cache/app-arch/torcx-0.2.0-r3
  metadata/md5-cache/app-arch/torcx-9999
  metadata/md5-cache/coreos-base/afterburn-4.0.0-r4
  metadata/md5-cache/coreos-base/afterburn-9999
  metadata/md5-cache/coreos-base/coreos-cloudinit-1.14.0-r1
  metadata/md5-cache/coreos-base/coreos-cloudinit-9999
  metadata/md5-cache/coreos-base/coreos-init-0.0.1-r164
  metadata/md5-cache/coreos-base/coreos-init-9999
  metadata/md5-cache/coreos-base/update-ssh-keys-0.3.0-r5
  metadata/md5-cache/coreos-base/update-ssh-keys-9999
  metadata/md5-cache/coreos-base/update_engine-0.4.10
  metadata/md5-cache/coreos-base/update_engine-9999
  metadata/md5-cache/coreos-devel/mantle-0.13.0-r1
  metadata/md5-cache/coreos-devel/mantle-9999
  metadata/md5-cache/sys-apps/baselayout-3.6.6
  metadata/md5-cache/sys-apps/baselayout-9999
  metadata/md5-cache/sys-apps/ignition-0.34.0
  metadata/md5-cache/sys-apps/ignition-9999
  metadata/md5-cache/sys-apps/seismograph-2.2.5-r1
  metadata/md5-cache/sys-apps/seismograph-9999
  metadata/md5-cache/sys-boot/grub-2.02-r5
  metadata/md5-cache/sys-boot/grub-9999
  metadata/md5-cache/sys-boot/shim-0.8_p20150423-r1
  metadata/md5-cache/sys-boot/shim-9999
  metadata/md5-cache/sys-kernel/bootengine-0.0.38-r1
  metadata/md5-cache/sys-kernel/bootengine-9999
  metadata/md5-cache/sys-kernel/coreos-kernel-4.19.102
  metadata/md5-cache/sys-kernel/coreos-kernel-4.19.89
  metadata/md5-cache/sys-kernel/coreos-modules-4.19.102
  metadata/md5-cache/sys-kernel/coreos-sources-4.19.102
  sys-kernel/coreos-kernel/coreos-kernel-4.19.102.ebuild
  sys-kernel/coreos-modules/coreos-modules-4.19.102.ebuild
  sys-kernel/coreos-modules/files/commonconfig-4.19
  sys-kernel/coreos-sources/Manifest
  sys-kernel/coreos-sources/coreos-sources-4.19.102.ebuild
Labels: alpha

#173 sys-apps/systemd: bump systemd v241 to address CVE-2020-1712 for alpha 2411
  metadata/md5-cache/sys-apps/systemd-241-r7
  metadata/md5-cache/sys-apps/systemd-9999
  sys-apps/systemd/systemd-241-r7.ebuild
  sys-apps/systemd/systemd-9999.ebuild
Labels: alpha

#178 app-admin/sudo: bump sudo to 1.8.31 for alpha
  app-admin/sudo/Manifest
  app-admin/sudo/sudo-1.8.31.ebuild
  profiles/coreos/arm64/package.accept_keywords
Labels: alpha

#180 app-emulation: bump docker-runc to 1.0.0_rc10 for alpha
  app-emulation/containerd/containerd-0.2.6.ebuild
  app-emulation/containerd/containerd-9999.ebuild
  app-emulation/docker-proxy/docker-proxy-9999.ebuild
  app-emulation/docker-runc/Manifest
  app-emulation/docker-runc/docker-runc-1.0.0_rc10.ebuild
  app-emulation/docker-runc/docker-runc-1.0.0_rc2_p136-r1.ebuild
  app-emulation/docker-runc/files/0001-Delay-unshare-of-clone-newipc-for-selinux.patch
  app-emulation/docker-runc/files/0001-nsenter-clone-proc-self-exe-to-avoid-exposing-host-b.patch
  app-emulation/docker/docker-17.03.2-r1.ebuild
  app-emulation/docker/docker-9999.ebuild
  app-torcx/docker/docker-17.03.ebuild
  app-torcx/docker/docker-19.03.ebuild
  metadata/md5-cache/app-emulation/containerd-0.2.6
  metadata/md5-cache/app-emulation/containerd-1.1.2-r1
  metadata/md5-cache/app-emulation/containerd-9999
  metadata/md5-cache/app-emulation/docker-17.03.2-r1
  metadata/md5-cache/app-emulation/docker-19.03.5
  metadata/md5-cache/app-emulation/docker-9999
  metadata/md5-cache/app-emulation/docker-proxy-0.8.0_p20180709
  metadata/md5-cache/app-emulation/docker-proxy-9999
  metadata/md5-cache/app-emulation/docker-runc-1.0.0_rc10
  metadata/md5-cache/app-emulation/docker-runc-1.0.0_rc2_p136-r1
  metadata/md5-cache/app-torcx/docker-17.03
  metadata/md5-cache/app-torcx/docker-19.03
Labels: alpha

#179 sys-apps/ignition: Remove patches included in the repository
  sys-apps/ignition/files/0001-providers-allow-FetchConfig-to-mutate-the-fetcher.patch
  sys-apps/ignition/files/0002-providers-aws-get-region-after-getting-config.patch
  sys-apps/ignition/ignition-0.33.0-r2.ebuild
  sys-apps/ignition/ignition-9999.ebuild
Labels: edge

#176 app-emulation: bump docker-runc to 1.0.0-rc10
  app-emulation/containerd/containerd-9999.ebuild
  app-emulation/docker-runc/Manifest
  app-emulation/docker-runc/docker-runc-1.0.0_rc10.ebuild
  app-emulation/docker/docker-9999.ebuild
  app-torcx/docker/docker-19.03.ebuild
  metadata/md5-cache/app-emulation/containerd-1.3.2
  metadata/md5-cache/app-emulation/containerd-9999
  metadata/md5-cache/app-emulation/docker-19.03.5
  metadata/md5-cache/app-emulation/docker-9999
  metadata/md5-cache/app-emulation/docker-runc-1.0.0_rc10
  metadata/md5-cache/app-torcx/docker-19.03
Labels: edge

#185 dev-lang/go: remove unnecessary Go version 1.13.2 for alpha
  dev-lang/go/Manifest
  dev-lang/go/go-1.13.2.ebuild
Labels: alpha

#183 sys-apps/systemd: bump systemd to v243 for edge
  sys-apps/systemd/systemd-243.ebuild
  sys-apps/systemd/systemd-9999.ebuild
Labels: edge

#189 app-emulation/docker-runc: Disable SELinux warnings
  app-emulation/docker-runc/docker-runc-1.0.0_rc10.ebuild
  app-emulation/docker-runc/files/0001-temporarily-disable-selinux.GetEnabled-error-checks.patch
Labels: alpha, bug
