Repository flatcar/coreos-overlay, pull requests merged in 2020-10, with the labels that each got.

#628 sys-kernel: compress modules with xz
  profiles/coreos/base/package.use
  sys-kernel/coreos-modules/files/commonconfig-5.8
Labels: enhancement, main

#622 eclass: exclude unnecessary architectures from DTC in Kernel
  eclass/coreos-kernel.eclass
Labels: enhancement, main

#623 app-emulation/containerd: add containerd-runc-shim-v*
  app-emulation/containerd/containerd-1.4.1-r1.ebuild
  app-emulation/containerd/containerd-9999.ebuild
Labels: main

#636 oem-qemu: Add OEM package for QEMU
  coreos-base/oem-qemu/files/grub.cfg
  coreos-base/oem-qemu/files/oem-release
  coreos-base/oem-qemu/metadata.xml
  coreos-base/oem-qemu/oem-qemu-0.0.1.ebuild
Labels: alpha

#629 sys-kernel: allow fips mode to be enabled
  sys-kernel/coreos-modules/files/commonconfig-5.4
Labels: lts

#630 move cryptsetup to the overlay
  profiles/coreos/base/package.use.mask
  sys-fs/cryptsetup/Manifest
  sys-fs/cryptsetup/cryptsetup-1.7.5.ebuild
  sys-fs/cryptsetup/cryptsetup-2.0.2.ebuild
  sys-fs/cryptsetup/cryptsetup-2.0.3.ebuild
  sys-fs/cryptsetup/files/1.6.7-dmcrypt.confd
  sys-fs/cryptsetup/files/1.6.7-dmcrypt.rc
  sys-fs/cryptsetup/files/setup-1.7.0.py
  sys-fs/cryptsetup/metadata.xml
Labels: lts

#642 coreos-base/coreos: Add diffutils to the base packages
  coreos-base/coreos/coreos-0.0.1.ebuild
Labels: alpha

#649 sys-kernel: remove blank kernel module nf-conntrack-ipv4
  sys-kernel/coreos-sources/coreos-sources-5.8.14.ebuild
  sys-kernel/coreos-sources/files/5.8/z0001-kbuild-derive-relative-path-for-srctree-from-CURDIR.patch
  sys-kernel/coreos-sources/files/5.8/z0002-tools-objtool-Makefile-Don-t-fail-on-fallthrough-wit.patch
  sys-kernel/coreos-sources/files/5.8/z0003-net-netfilter-add-nf_conntrack_ipv4-compat-module-fo.patch
Labels: enhancement, main

#655 dev-lang/go: update Go to 1.12.17, remove Go 1.10
  coreos-base/hard-host-depends/hard-host-depends-0.0.1.ebuild
  dev-lang/go/Manifest
  dev-lang/go/go-1.10.8.ebuild
  dev-lang/go/go-1.12.17.ebuild
Labels: main

#658 profiles: gdbus-codegen only for python 3.6
  profiles/coreos/base/package.use
Labels: main
