Repository flatcar/coreos-overlay, pull requests merged in 2021-06, with the labels that each got.

#1035 profiles: accept keywords ~amd64 and ~arm64 for libxml2 2.9.12-r2
  profiles/coreos/base/package.accept_keywords
Labels: alpha, main

#1041 app-arch/torcx: update crypto and net, fix build issues
  app-arch/torcx/torcx-0.2.0-r4.ebuild
  app-arch/torcx/torcx-9999.ebuild
Labels: alpha, main

#1069 Revert "profiles: Update the accept keywords for curl 7.76.1"
  profiles/coreos/base/package.accept_keywords
Labels: channel/alpha, main

#1076 sys-apps/systemd: depend on lz4 >= 1.9.3-r1
  sys-apps/systemd/systemd-9999.ebuild
Labels: alpha, main

#1077 sys-firmware/intel-microcode: update to 20210608
  sys-firmware/intel-microcode/Manifest
  sys-firmware/intel-microcode/intel-microcode-20210608_p20210608.ebuild
Labels: alpha, main

#1078 coreos-base/oem-ec2-compat: Add NVIDIA support for AWS Pro
  coreos-base/oem-ec2-compat/files/base/base-aws-pro.ign
  coreos-base/oem-ec2-compat/oem-ec2-compat-0.1.2.ebuild
Labels: flatcar-2905, main
