Repository flatcar/coreos-overlay, pull requests merged in 2021-01, with the labels that each got.

#772 .github: fix env vars and sed expressions
  .github/workflows/containerd-apply-patch.sh
  .github/workflows/containerd-releases-main.yml
  .github/workflows/docker-releases-main.yml
  .github/workflows/go-releases-main.yml
  .github/workflows/kernel-apply-patch.sh
  .github/workflows/kernel-releases-alpha.yml
  .github/workflows/kernel-releases-beta.yml
  .github/workflows/kernel-releases-main.yml
  .github/workflows/kernel-releases-stable.yml
  .github/workflows/runc-apply-patch.sh
  .github/workflows/runc-releases-main.yml
  .github/workflows/rust-apply-patch.sh
  .github/workflows/rust-release-main.yml
Labels: bug, github-actions

#773 dev-util/bsdiff: fix heap overflow vulnerability CVE-2020-14315
  dev-util/bsdiff/bsdiff-4.3-r8.ebuild
  dev-util/bsdiff/files/bsdiff-4.3-CVE-2020-14315.patch
Labels: alpha, main

#782 profiles: disable cxx for net-libs/nghttp2
  profiles/coreos/base/package.use
Labels: alpha, main

#795 app-emulation/open-vm-tools: update to 11.2.5
  app-emulation/open-vm-tools/Manifest
  app-emulation/open-vm-tools/files/open-vm-tools-11.2.5-0001-configure-Add-options-for-fuse-hgfs-and-udev.patch
  app-emulation/open-vm-tools/open-vm-tools-11.2.5.ebuild
  coreos-base/oem-vmware/oem-vmware-11.2.5.ebuild
Labels: alpha, main

#800 coreos-base,profiles: delete nss
  coreos-devel/sdk-depends/sdk-depends-0.0.1.ebuild
  profiles/coreos/arm64/package.accept_keywords
  profiles/coreos/base/package.use
  profiles/coreos/targets/generic/package.use
Labels: alpha, main

#791 sys-block/open-iscsi: Update iscsi to 2.1.3
  sys-block/open-iscsi/Manifest
  sys-block/open-iscsi/files/initiatorname.iscsi
  sys-block/open-iscsi/files/iscsi-init.service
  sys-block/open-iscsi/files/iscsid-conf.d
  sys-block/open-iscsi/files/iscsid-initiatorname.service
  sys-block/open-iscsi/files/iscsid.service
  sys-block/open-iscsi/files/iscsid.socket
  sys-block/open-iscsi/files/open-iscsi-2.0.873-Makefiles.patch
  sys-block/open-iscsi/files/open-iscsi-2.0.873-remove-kernel-version-check.patch
  sys-block/open-iscsi/files/open-iscsi-2.1.1-Makefiles.patch
  sys-block/open-iscsi/metadata.xml
  sys-block/open-iscsi/open-iscsi-2.0.873-r3.ebuild
  sys-block/open-iscsi/open-iscsi-2.1.3.ebuild
Labels: alpha, flatcar-2605, flatcar-2705

#802 coreos-base/hard-host-depends: bring back dependency on dev-libs/nspr
  coreos-base/hard-host-depends/hard-host-depends-0.0.1-r195.ebuild
  coreos-base/hard-host-depends/hard-host-depends-0.0.1.ebuild
Labels: alpha, bug, main
