Repository flatcar/coreos-overlay, pull requests merged in 2021-08, with the labels that each got.

#1129 .github: list only ebuilds with a unique VERSION_OLD for runc
  .github/workflows/containerd-apply-patch.sh
  .github/workflows/docker-apply-patch.sh
  .github/workflows/firmware-apply-patch.sh
  .github/workflows/go-apply-patch.sh
  .github/workflows/runc-apply-patch.sh
  .github/workflows/rust-apply-patch.sh
Labels: bug, github-actions

#934 dev-util/boost-build: delete boost-build 1.67
  dev-util/boost-build/Manifest
  dev-util/boost-build/boost-build-1.63.0.ebuild
  dev-util/boost-build/boost-build-1.65.0.ebuild
  dev-util/boost-build/boost-build-1.66.0.ebuild
  dev-util/boost-build/boost-build-1.67.0.ebuild
  dev-util/boost-build/files/boost-build-1.48.0-disable_python_rpath.patch
  dev-util/boost-build/files/boost-build-1.49.0-darwin-gentoo-toolchain.patch
  dev-util/boost-build/files/boost-build-1.50.0-respect-c_ld-flags.patch
  dev-util/boost-build/files/boost-build-1.52.0-darwin-no-python-framework.patch
  dev-util/boost-build/files/boost-build-1.54.0-fix-test.patch
  dev-util/boost-build/files/boost-build-1.54.0-support_dots_in_python-buildid.patch
  dev-util/boost-build/files/boost-build-1.55.0-ppc-aix.patch
  dev-util/boost-build/files/boost-build-1.62.0-sparc-no-default-flags.patch
  dev-util/boost-build/files/boost-build-1.66.0-add-none-feature-options.patch
  dev-util/boost-build/files/site-config.jam
  dev-util/boost-build/metadata.xml
Labels: alpha, main

#933 profiles: delete ccache completely
  coreos-base/hard-host-depends/hard-host-depends-0.0.1.ebuild
  profiles/coreos/base/make.defaults
  profiles/coreos/targets/sdk/make.defaults
  profiles/coreos/targets/sdk/package.use
Labels: alpha, main

#1181 sec-policy/selinux-virt: add rules to run `flannel` with SELinux enforced mode
  sec-policy/selinux-virt/files/virt.patch
Labels: alpha, beta, main

#1183 app-crypt/mit-krb5: update to 1.19.2
  app-crypt/mit-krb5/Manifest
  app-crypt/mit-krb5/files/CVE-2020-28196.patch
  app-crypt/mit-krb5/files/mit-krb5-1.18.2-autoconf-2.70.patch
  app-crypt/mit-krb5/files/mit-krb5_dont_create_run.patch
  app-crypt/mit-krb5/mit-krb5-1.19.2.ebuild
Labels: alpha

#1189 sys-apps/systemd: Updates to v247.9
  sys-apps/systemd/Manifest
  sys-apps/systemd/systemd-247.9.ebuild
Labels: alpha, stable, beta

#1207 coreos-devel/sdk-extras: delete sdk-extras
  app-portage/repoman/Manifest
  app-portage/repoman/README.md
  app-portage/repoman/metadata.xml
  app-portage/repoman/repoman-3.0.2.ebuild
  coreos-base/hard-host-depends/hard-host-depends-0.0.1.ebuild
  coreos-devel/sdk-extras/sdk-extras-0.0.1-r5.ebuild
  coreos-devel/sdk-extras/sdk-extras-0.0.1.ebuild
  profiles/coreos/base/package.use
  profiles/coreos/targets/sdk/package.accept_keywords
Labels: alpha, main

#1210 dev-util/strace: move to portage-stable
  dev-util/strace/Manifest
  dev-util/strace/files/strace-5.4-fix-LTO-CFLAGS-handling.patch
  dev-util/strace/files/strace-5.5-static.patch
  dev-util/strace/metadata.xml
  dev-util/strace/strace-5.6.ebuild
  dev-util/strace/strace-5.9.ebuild
  profiles/coreos/base/package.accept_keywords
Labels: alpha, main

#1200 app-emulation/wa-linux-agent: Update to 2.3.1.1
  app-emulation/wa-linux-agent/Manifest
  app-emulation/wa-linux-agent/wa-linux-agent-2.3.1.1.ebuild
  coreos-base/oem-azure-pro/oem-azure-pro-2.3.1.1.ebuild
  coreos-base/oem-azure/oem-azure-2.3.1.1.ebuild
Labels: alpha

#1214 explicitly set 'runtime_type' in containerd config
  app-emulation/containerd/containerd-1.5.5-r1.ebuild
  app-emulation/containerd/files/config-cgroupfs.toml
  app-emulation/containerd/files/config.toml
Labels: channel/alpha

#1237 sys-kernel/coreos-modules: add Intel E800 series network adapter driver
  sys-kernel/coreos-modules/files/commonconfig-5.10
Labels: main
