Repository flatcar/coreos-overlay, pull requests merged in 2021-02, with the labels that each got.

#816 app-emulation/cri-tools: add a new package
  app-emulation/cri-tools/Manifest
  app-emulation/cri-tools/cri-tools-1.19.0.ebuild
  app-emulation/cri-tools/metadata.xml
  coreos-base/coreos/coreos-0.0.1-r298.ebuild
  coreos-base/coreos/coreos-0.0.1.ebuild
Labels: alpha, main

#826 app-emulation,torcx: delete docker 1.12
  app-arch/torcx/files/docker-1.12-yes.json
  app-arch/torcx/torcx-9999.ebuild
  app-emulation/containerd/Manifest
  app-emulation/containerd/containerd-0.2.5-r3.ebuild
  app-emulation/docker-runc/docker-runc-1.0.0_rc2_p136-r1.ebuild
  app-emulation/docker-runc/docker-runc-1.0.0_rc92.ebuild
  app-emulation/docker/docker-1.12.6-r8.ebuild
  app-emulation/runc/Manifest
  app-emulation/runc/files/0001-Makefile-do-not-install-dependencies-of-target.patch
  app-emulation/runc/files/0001-nsenter-clone-proc-self-exe-to-avoid-exposing-host-b_1.12.patch
  app-emulation/runc/files/0002-1.0.0_rc2_p9-Fix-setting-selinux-label-for-mqueue-under-userns.patch
  app-emulation/runc/metadata.xml
  app-emulation/runc/runc-1.0.0_rc2_p9-r1.ebuild
  app-torcx/docker/docker-1.12.ebuild
  app-torcx/docker/files/docker-1.12-manifest.json
  profiles/coreos/amd64/generic/package.use
Labels: alpha, main

#827 dev-lang/go: delete go 1.6
  coreos-base/hard-host-depends/hard-host-depends-0.0.1-r196.ebuild
  coreos-base/hard-host-depends/hard-host-depends-0.0.1.ebuild
  dev-lang/go/Manifest
  dev-lang/go/go-1.6.3-r1.ebuild
Labels: alpha, main

#839 sys-firmware/intel-microcode: Update to 20201112
  sys-firmware/intel-microcode/Manifest
  sys-firmware/intel-microcode/intel-microcode-20201112_p20201116-r1.ebuild
Labels: alpha

#842 x11-drivers/nvidia-metadata: Fix the version number of the ebuild file
  x11-drivers/nvidia-metadata/nvidia-metadata-460.32.03.ebuild
Labels: flatcar-2765

#853 .github: Minor fixes in kernel update workflow
  .github/workflows/kernel-apply-patch.sh
Labels: github-actions

#856 dev-util/catalyst: Use python3 in scripts explicitly
  dev-util/catalyst/README.md
  dev-util/catalyst/catalyst-3.0.14-r1.ebuild
  dev-util/catalyst/files/0001-catalyst-Remove-left-over-Id.patch
  dev-util/catalyst/files/0002-catalyst-Remove-Maintained-by-sections.patch
  dev-util/catalyst/files/0003-catalyst-Remove-unnecessary-future-imports.patch
  dev-util/catalyst/files/0004-catalyst-Use-python3-shebangs.patch
Labels: bug

#858 delete dhcpcd, containerd-stress
  app-emulation/containerd/containerd-1.4.3-r1.ebuild
  app-emulation/containerd/containerd-9999.ebuild
  coreos-base/coreos/coreos-0.0.1-r299.ebuild
  coreos-base/coreos/coreos-0.0.1.ebuild
  coreos-base/hard-host-depends/hard-host-depends-0.0.1-r197.ebuild
  coreos-base/hard-host-depends/hard-host-depends-0.0.1.ebuild
Labels: alpha, enhancement
