Repository flatcar/coreos-overlay, pull requests merged in 2021-04, with the labels that each got.

#947 app-emulation/cri-tools: update checksums
  app-emulation/cri-tools/Manifest
Labels: alpha, main

#941 dev-lang/go: Bump the default Go version to 1.16
  .github/workflows/go-apply-patch.sh
  .github/workflows/go-releases-main.yml
  app-admin/sdnotify-proxy/sdnotify-proxy-9999.ebuild
  app-arch/torcx/torcx-9999.ebuild
  app-crypt/go-tspi/go-tspi-9999.ebuild
  app-emulation/actool/actool-9999.ebuild
  app-emulation/amazon-ssm-agent/amazon-ssm-agent-2.3.1319.0.ebuild
  coreos-base/coreos-cloudinit/coreos-cloudinit-9999.ebuild
  coreos-base/hard-host-depends/hard-host-depends-0.0.1.ebuild
  coreos-base/nova-agent-watcher/nova-agent-watcher-9999.ebuild
  dev-db/etcdctl/etcdctl-3.3.25.ebuild
  dev-lang/go/Manifest
  dev-lang/go/go-1.16.2.ebuild
  eclass/coreos-go-utils.eclass
  sys-apps/ignition/ignition-9999.ebuild
Labels: alpha, main

#959 Set the default Go version to 1.16
  app-admin/updateservicectl/updateservicectl-9999.ebuild
  app-emulation/acbuild/acbuild-9999.ebuild
  app-emulation/cri-tools/cri-tools-1.19.0.ebuild
  eclass/coreos-go-depend.eclass
  eclass/coreos-go.eclass
Labels: alpha, bug, main

#962 app-emulation/cri-tools: update checksums
  app-emulation/cri-tools/Manifest
Labels: flatcar-2801

#963 app-emulation/cri-tools: update checksums
  app-emulation/cri-tools/Manifest
Labels: flatcar-2823

#960 profiles: accept keywords for net-libs/gnutls
  profiles/coreos/base/package.accept_keywords
Labels: alpha, main

#964 app-emulation: update qemu to 5.2.0
  app-emulation/qemu/Manifest
  app-emulation/qemu/files/65-kvm.rules-r2
  app-emulation/qemu/files/qemu-2.5.0-cflags.patch
  app-emulation/qemu/files/qemu-2.5.0-sysmacros.patch
  app-emulation/qemu/files/qemu-3.1.0-md-clear-md-no.patch
  app-emulation/qemu/files/qemu-4.0.0-fix_infiniband_include.patch
  app-emulation/qemu/files/qemu-4.0.0-linux-headers-5.2.patch
  app-emulation/qemu/files/qemu-4.0.0-mkdir_systemtap.patch
  app-emulation/qemu/files/qemu-4.0.0-pc-q35-4.0.patch
  app-emulation/qemu/files/qemu-4.0.0-sanitize-interp_info.patch
  app-emulation/qemu/files/qemu-4.0.0-xkbcommon.patch
  app-emulation/qemu/files/qemu-4.2.0-cflags.patch
  app-emulation/qemu/files/qemu-5.0.0-epoll-strace.patch
  app-emulation/qemu/files/qemu-5.2.0-cleaner-werror.patch
  app-emulation/qemu/files/qemu-5.2.0-disable-keymap.patch
  app-emulation/qemu/files/qemu-5.2.0-fix-firmware-path.patch
  app-emulation/qemu/files/qemu-5.2.0-no-pie-ld.patch
  app-emulation/qemu/files/qemu-5.2.0-strings.patch
  app-emulation/qemu/files/qemu-9999-fix-firmware-path.patch
  app-emulation/qemu/metadata.xml
  app-emulation/qemu/qemu-5.2.0-r2.ebuild
  profiles/coreos/base/package.use
Labels: alpha, main

#971 sys-apps/systemd: Fix the patch to update DefaultTasksMax
  sys-apps/systemd/files/0007-core-use-max-for-DefaultTasksMax.patch
Labels: alpha, flatcar-2605, flatcar-2765, flatcar-2801, flatcar-2823, main

#973 profiles: Add accept keywords for openldap
  profiles/coreos/base/package.accept_keywords
Labels: alpha, main

#975 sys-apps/systemd: Sync with Gentoo upstream; updates to 247.6
  sys-apps/systemd/Manifest
  sys-apps/systemd/systemd-247.6.ebuild
Labels: flatcar-2823

#977 sys-apps/systemd: Re-adjust the defaults tasks patch for v246
  sys-apps/systemd/files/0007-core-use-max-for-DefaultTasksMax.patch
Labels: flatcar-lts-2605

#974 profiles: Update the accept keywords for curl 7.76.1
  profiles/coreos/base/package.accept_keywords
Labels: alpha, main

#978 sys-app/systemd: Update systemd 247.6
  sys-apps/systemd/Manifest
  sys-apps/systemd/systemd-247.6.ebuild
Labels: alpha, main
