Repository flatcar/coreos-overlay, pull requests merged in 2021-11, with the labels that each got.

#1382 selinux-base: fix build issue during boostrap
  sec-policy/selinux-base/selinux-base-2.20200818-r2.ebuild
Labels: main

#1386 *: use https instead of git for Github URLs
  app-admin/locksmith/locksmith-9999.ebuild
  app-admin/mayday/mayday-9999.ebuild
  app-admin/sdnotify-proxy/sdnotify-proxy-9999.ebuild
  app-admin/toolbox/toolbox-9999.ebuild
  app-admin/updateservicectl/updateservicectl-9999.ebuild
  app-arch/torcx/torcx-9999.ebuild
  app-crypt/go-tspi/go-tspi-9999.ebuild
  app-emulation/acbuild/acbuild-9999.ebuild
  app-emulation/actool/actool-9999.ebuild
  coreos-base/afterburn/afterburn-9999.ebuild
  coreos-base/coreos-cloudinit/coreos-cloudinit-9999.ebuild
  coreos-base/coreos-init/coreos-init-9999.ebuild
  coreos-base/emerge-gitclone/emerge-gitclone-9999.ebuild
  coreos-base/nova-agent-watcher/nova-agent-watcher-9999.ebuild
  coreos-base/update-ssh-keys/update-ssh-keys-9999.ebuild
  coreos-base/update_engine/update_engine-9999.ebuild
  coreos-devel/fero-client/fero-client-9999.ebuild
  coreos-devel/mantle/mantle-9999.ebuild
  profiles/coreos/arm64/package.accept_keywords
  sys-apps/baselayout/baselayout-9999.ebuild
  sys-apps/ignition/ignition-9999.ebuild
  sys-apps/seismograph/seismograph-9999.ebuild
  sys-boot/grub/grub-9999.ebuild
  sys-boot/shim/shim-9999.ebuild
  sys-kernel/bootengine/bootengine-9999.ebuild
  sys-libs/nss-usrfiles/nss-usrfiles-9999.ebuild
Labels: bug, alpha, stable, beta, main, lts

#1381 profiles: accept keywords for wget 1.21.2.
  profiles/coreos/base/package.accept_keywords
Labels: main

#1383 sys-libs/ncurses: update to 6.2_p20210619
  app-emulation/qemu/qemu-5.2.0-r2.ebuild
  profiles/coreos/arm64/package.use
  sys-libs/ncurses/Manifest
  sys-libs/ncurses/files/ncurses-5.9-gcc-5.patch
  sys-libs/ncurses/files/ncurses-6.2-no_user_ldflags_in_libs.patch
  sys-libs/ncurses/files/ncurses-6.2_p20210123-cppflags-cross.patch
  sys-libs/ncurses/metadata.xml
  sys-libs/ncurses/ncurses-6.2_p20210619.ebuild
Labels: main

#1387 *: replace git:// with https:// for Github URLs
  app-emulation/docker/docker-1.12.6-r8.ebuild
  app-emulation/docker/docker-17.03.2-r1.ebuild
  app-emulation/rkt/rkt-9999.ebuild
  coreos-base/cros-devutils/cros-devutils-9999.ebuild
Labels: bug, lts

#1388 Revert back to git:// URLs
  app-admin/locksmith/locksmith-9999.ebuild
  app-admin/mayday/mayday-9999.ebuild
  app-admin/sdnotify-proxy/sdnotify-proxy-9999.ebuild
  app-admin/toolbox/toolbox-9999.ebuild
  app-admin/updateservicectl/updateservicectl-9999.ebuild
  app-arch/torcx/torcx-9999.ebuild
  app-crypt/go-tspi/go-tspi-9999.ebuild
  app-emulation/acbuild/acbuild-9999.ebuild
  app-emulation/actool/actool-9999.ebuild
  coreos-base/afterburn/afterburn-9999.ebuild
  coreos-base/coreos-cloudinit/coreos-cloudinit-9999.ebuild
  coreos-base/coreos-init/coreos-init-9999.ebuild
  coreos-base/emerge-gitclone/emerge-gitclone-9999.ebuild
  coreos-base/nova-agent-watcher/nova-agent-watcher-9999.ebuild
  coreos-base/update-ssh-keys/update-ssh-keys-9999.ebuild
  coreos-base/update_engine/update_engine-9999.ebuild
  coreos-devel/fero-client/fero-client-9999.ebuild
  coreos-devel/mantle/mantle-9999.ebuild
  profiles/coreos/arm64/package.accept_keywords
  sys-apps/baselayout/baselayout-9999.ebuild
  sys-apps/ignition/ignition-9999.ebuild
  sys-apps/seismograph/seismograph-9999.ebuild
  sys-boot/grub/grub-9999.ebuild
  sys-boot/shim/shim-9999.ebuild
  sys-kernel/bootengine/bootengine-9999.ebuild
  sys-libs/nss-usrfiles/nss-usrfiles-9999.ebuild
Labels: bug, alpha, stable, beta, main, lts

#1389 `dev-libs/openssl`: enable `fips` support
  dev-libs/openssl/Manifest
  dev-libs/openssl/metadata.xml
  dev-libs/openssl/openssl-1.1.1l-r1.ebuild
  dev-libs/openssl/openssl-3.0.0.ebuild
  profiles/coreos/base/package.use
Labels: alpha, main

#1394 *: *: use https instead of git for Github URLs (take 2)
  app-admin/locksmith/locksmith-9999.ebuild
  app-admin/mayday/mayday-9999.ebuild
  app-admin/sdnotify-proxy/sdnotify-proxy-9999.ebuild
  app-admin/toolbox/toolbox-9999.ebuild
  app-admin/updateservicectl/updateservicectl-9999.ebuild
  app-arch/torcx/torcx-9999.ebuild
  app-crypt/go-tspi/go-tspi-9999.ebuild
  app-emulation/acbuild/acbuild-9999.ebuild
  app-emulation/actool/actool-9999.ebuild
  coreos-base/afterburn/afterburn-9999.ebuild
  coreos-base/coreos-cloudinit/coreos-cloudinit-9999.ebuild
  coreos-base/coreos-init/coreos-init-9999.ebuild
  coreos-base/emerge-gitclone/emerge-gitclone-9999.ebuild
  coreos-base/nova-agent-watcher/nova-agent-watcher-9999.ebuild
  coreos-base/update-ssh-keys/update-ssh-keys-9999.ebuild
  coreos-base/update_engine/update_engine-9999.ebuild
  coreos-devel/fero-client/fero-client-9999.ebuild
  coreos-devel/mantle/mantle-9999.ebuild
  profiles/coreos/arm64/package.accept_keywords
  profiles/coreos/base/make.defaults
  sys-apps/baselayout/baselayout-9999.ebuild
  sys-apps/ignition/ignition-9999.ebuild
  sys-apps/seismograph/seismograph-9999.ebuild
  sys-boot/grub/grub-9999.ebuild
  sys-boot/shim/shim-9999.ebuild
  sys-kernel/bootengine/bootengine-9999.ebuild
  sys-libs/nss-usrfiles/nss-usrfiles-9999.ebuild
Labels: bug, alpha, stable, beta, main, lts

#1395 sys-apps/baselayout: Add sgx group
  sys-apps/baselayout/baselayout-3.6.8-r3.ebuild
  sys-apps/baselayout/baselayout-9999.ebuild
Labels: main

#1397 sys-kernel/bootengine: Stop using deprecated actions in veritysetup
  sys-kernel/bootengine/bootengine-0.0.38-r11.ebuild
  sys-kernel/bootengine/bootengine-9999.ebuild
Labels: main

#1384 profiles: delete unnecessary accept_keywords
  coreos-devel/sdk-depends/sdk-depends-0.0.1.ebuild
  profiles/coreos/arm64/package.accept_keywords
  profiles/coreos/base/package.accept_keywords
  profiles/coreos/base/package.use
  profiles/coreos/targets/sdk/package.accept_keywords
  profiles/features/systemd/package.accept_keywords
Labels: main

#1400 dev-lang/go: Upgrade Go 1.16.9 to 1.16.10
  dev-lang/go/Manifest
  dev-lang/go/go-1.16.10.ebuild
Labels: stable, flatcar-2983

#1370 Move logrotate to coreos-overlay from portage-stable
  app-admin/logrotate/Manifest
  app-admin/logrotate/files/logrotate-3.15.0-ignore-hidden.patch
  app-admin/logrotate/files/logrotate.conf
  app-admin/logrotate/files/logrotate.service
  app-admin/logrotate/files/logrotate.tmpfiles
  app-admin/logrotate/logrotate-3.18.1-r1.ebuild
  app-admin/logrotate/metadata.xml
  coreos-base/coreos-init/coreos-init-9999.ebuild
Labels: main

#1410 profiles: exclude unicode USE flag from app-editors/nano
  profiles/coreos/base/package.use.mask
Labels: bug, alpha, main

#1406 profiles: Changes related to package updates in portage-stable (getting rid of EAPI 3)
  profiles/coreos/arm64/package.accept_keywords
  profiles/coreos/targets/generic/package.provided
Labels: main

#1407 profiles: add missing arm64 sdk keywords
  profiles/coreos/arm64/package.accept_keywords
Labels: main

#1414 dev-embedded/u-boot-tools: Update to v2021.04_rc2 for arm64
  profiles/coreos/arm64/package.accept_keywords
Labels: main

#1411 Upgrade net-libs/rpcsvs-proto to 1.9.4
  net-libs/rpcsvc-proto/Manifest
  net-libs/rpcsvc-proto/files/rpcsvc-proto-1.3.1-old-preprocessor.patch
  net-libs/rpcsvc-proto/metadata.xml
  net-libs/rpcsvc-proto/rpcsvc-proto-0.ebuild
  net-libs/rpcsvc-proto/rpcsvc-proto-1.3.1-r1.ebuild
  net-libs/rpcsvc-proto/rpcsvc-proto-1.4.2.ebuild
  net-libs/rpcsvc-proto/rpcsvc-proto-1.4.ebuild
Labels: main

#1357 Adapt to new pkg-config implementation
  app-crypt/p11-kit/Manifest
  app-crypt/p11-kit/README.md
  app-crypt/p11-kit/metadata.xml
  app-crypt/p11-kit/p11-kit-0.23.22.ebuild
  coreos-base/update_engine/update_engine-9999.ebuild
  dev-libs/dbus-glib/Manifest
  dev-libs/dbus-glib/dbus-glib-0.112.ebuild
  dev-libs/dbus-glib/metadata.xml
  profiles/coreos/targets/generic/package.use
  sys-apps/systemd/systemd-9999.ebuild
  sys-auth/sssd/sssd-2.3.1-r3.ebuild
  sys-fs/btrfs-progs/Manifest
  sys-fs/btrfs-progs/README.md
  sys-fs/btrfs-progs/btrfs-progs-5.10.1-r1.ebuild
  sys-fs/btrfs-progs/metadata.xml
  sys-fs/lvm2/README.md
  sys-fs/lvm2/lvm2-2.02.188-r2.ebuild
Labels: main

#1420 .github: add Github Actions for ca-certificates
  .github/workflows/cacerts-apply-patch.sh
  .github/workflows/cacerts-releases-alpha.yml
  .github/workflows/cacerts-releases-beta.yml
  .github/workflows/cacerts-releases-lts-2021.yml
  .github/workflows/cacerts-releases-main.yaml
  .github/workflows/cacerts-releases-stable.yml
Labels: github-actions

#1425 .github: fix version delimiter of ca-certs workflow for main
  .github/workflows/cacerts-releases-main.yaml
Labels: bug, github-actions

#1426 sec-policy/selinux-base-policy: add capability to unlabeled_t
  sec-policy/selinux-base-policy/files/unlabeled.patch
  sec-policy/selinux-base-policy/selinux-base-policy-2.20200818-r2.ebuild
Labels: alpha, stable, beta, main

#1431 profiles: accept keywords for rsync 3.2.3-r5
  profiles/coreos/base/package.accept_keywords
Labels: main

#1408 Upgrade net-libs/libmicrohttpd to 0.9.73
  profiles/coreos/base/package.accept_keywords
Labels: main

#1445 profiles: delete unnecessary keywords for gcc
  profiles/coreos/arm64/package.accept_keywords
  profiles/coreos/base/package.accept_keywords
Labels: main

#1444 app-admin/etcd-wrapper: remove `ETCD_NAME`
  app-admin/etcd-wrapper/files/etcd-wrapper
Labels: stable, beta, main
