Repository flatcar/coreos-overlay, pull requests merged in 2021-05, with the labels that each got.

#998 sys-apps/dbus: update to 1.10.32
  sys-apps/dbus/Manifest
  sys-apps/dbus/dbus-1.10.32.ebuild
  sys-apps/dbus/files/CVE-2019-12749.patch
Labels: alpha, main

#1014 x11-drivers/nvidia-{drivers,metadata}: Update the version to 460.73.01
  x11-drivers/nvidia-drivers/nvidia-drivers-460.73.01.ebuild
  x11-drivers/nvidia-metadata/files/nvidia-metadata
  x11-drivers/nvidia-metadata/nvidia-metadata-460.73.01.ebuild
Labels: alpha, main

#1015 sys-apps/systemd: update systemd to 246.13
  sys-apps/systemd/Manifest
  sys-apps/systemd/files/0007-core-use-max-for-DefaultTasksMax.patch
  sys-apps/systemd/systemd-246.13.ebuild
Labels: flatcar-lts-2605, lts

#1022 profiles,sys-boot: fix grub2 for binutils 2.36
  profiles/coreos/base/package.accept_keywords
  sys-boot/grub/files/grub-2.02-binutils-2.36-x86-used-note.patch
  sys-boot/grub/grub-2.02-r6.ebuild
  sys-boot/grub/grub-9999.ebuild
Labels: alpha, main

#1023 net-misc/openssh: update to 8.6
  net-misc/openssh/Manifest
  net-misc/openssh/files/openssh-8.0_p1-hpn-14.20-X509-glue.patch
  net-misc/openssh/files/openssh-8.1_p1-X509-12.3-tests.patch
  net-misc/openssh/files/openssh-8.1_p1-X509-glue-12.3.patch
  net-misc/openssh/files/openssh-8.1_p1-hpn-14.20-sctp-glue.patch
  net-misc/openssh/files/openssh-8.1_p1-tests-2020.patch
  net-misc/openssh/files/openssh-8.2_p1-X509-12.4.3-tests.patch
  net-misc/openssh/files/openssh-8.2_p1-X509-glue-12.4.3.patch
  net-misc/openssh/files/openssh-8.2_p1-hpn-14.20-glue.patch
  net-misc/openssh/files/openssh-8.2_p1-hpn-14.20-libressl.patch
  net-misc/openssh/files/openssh-8.2_p1-hpn-14.20-sctp-glue.patch
  net-misc/openssh/files/openssh-8.3_p1-X509-glue-12.5.1.patch
  net-misc/openssh/files/openssh-8.3_p1-hpn-14.20-glue.patch
  net-misc/openssh/files/openssh-8.4_p1-X509-glue-12.6.patch
  net-misc/openssh/files/openssh-8.4_p1-fix-ssh-copy-id.patch
  net-misc/openssh/files/openssh-8.4_p1-hpn-14.22-X509-glue.patch
  net-misc/openssh/files/openssh-8.4_p1-hpn-14.22-glue.patch
  net-misc/openssh/files/openssh-8.4_p1-hpn-14.22-sctp-glue.patch
  net-misc/openssh/files/openssh-8.5_p1-GSSAPI-dns.patch
  net-misc/openssh/files/openssh-8.5_p1-X509-glue-13.0.1.patch
  net-misc/openssh/files/openssh-8.5_p1-X509-glue-13.0.patch
  net-misc/openssh/files/openssh-8.5_p1-hpn-15.1-X509-glue.patch
  net-misc/openssh/files/openssh-8.5_p1-hpn-15.1-glue.patch
  net-misc/openssh/files/openssh-8.5_p1-hpn-15.1-sctp-glue.patch
  net-misc/openssh/files/openssh-8.5_p1-hpn-15.2-X509-13.0.1-glue.patch
  net-misc/openssh/files/openssh-8.5_p1-hpn-15.2-glue.patch
  net-misc/openssh/files/openssh-8.5_p1-hpn-15.2-sctp-glue.patch
  net-misc/openssh/files/openssh-8.6_p1-X509-glue-13.1.patch
  net-misc/openssh/files/openssh-8.6_p1-hpn-15.2-X509-glue.patch
  net-misc/openssh/files/openssh-8.6_p1-hpn-15.2-glue.patch
  net-misc/openssh/files/openssh-8.6_p1-hpn-version.patch
  net-misc/openssh/files/sshd.service
  net-misc/openssh/files/sshd_at.service
  net-misc/openssh/openssh-8.4_p1-r3.ebuild
  net-misc/openssh/openssh-8.5_p1-r1.ebuild
  net-misc/openssh/openssh-8.5_p1.ebuild
  net-misc/openssh/openssh-8.6_p1-r1.ebuild
  profiles/coreos/base/package.accept_keywords
Labels: alpha, main

#1029 coreos-base/update_engine: bump commit ID
  coreos-base/update_engine/update_engine-9999.ebuild
Labels: alpha, bug, flatcar-2765, flatcar-2823, flatcar-2879, flatcar-lts-2605, main
