Repository flatcar/coreos-overlay, pull requests merged in 2021-09, with the labels that each got.

#1241 sys-kernel/coreos-firmware: fix symlink to Intel ICE firmware
  sys-kernel/coreos-firmware/coreos-firmware-20210818-r1.ebuild
  sys-kernel/coreos-firmware/coreos-firmware-99999999.ebuild
Labels: bug, main, flatcar-2823

#1242 profiles: accept keyword ~arm64 for selinux
  profiles/coreos/arm64/package.accept_keywords
Labels: bug, main

#1195 coreos-devel/mantle: update to v0.16.0
  coreos-devel/mantle/mantle-0.16.0.ebuild
  coreos-devel/mantle/mantle-9999.ebuild
Labels: main

#1247 .github: fetch the correct Flatcar image signing key
  .github/workflows/setup-flatcar-sdk.sh
Labels: bug, github-actions

#1236 coreos-modules: add GPIO support
  sys-kernel/coreos-modules/files/commonconfig-5.10
Labels: main

#1243 sys-libs/glibc: update to 2.33-r7
  sys-libs/glibc/Manifest
  sys-libs/glibc/files/host.conf-1
  sys-libs/glibc/glibc-2.33-r7.ebuild
Labels: main

#1246 app-misc/ca-certificates: consider system encoding when opening file
  app-misc/ca-certificates/ca-certificates-3.27.1-r3.ebuild
  app-misc/ca-certificates/files/certdata2pem.py
Labels: bug, main

#1250 app-emulation/xenstore: Update to 4.14.2
  app-emulation/xenstore/Manifest
  app-emulation/xenstore/files/Tools.mk
  app-emulation/xenstore/files/config.h
  app-emulation/xenstore/xenstore-4.14.2.ebuild
Labels: main

#1251 net-misc/openssh: update to 8.7_p1-r1
  net-misc/openssh/Manifest
  net-misc/openssh/files/openssh-8.0_p1-hpn-version.patch
  net-misc/openssh/files/openssh-8.3_p1-sha2-include.patch
  net-misc/openssh/files/openssh-8.4_p1-X509-glue-12.6.patch
  net-misc/openssh/files/openssh-8.4_p1-fix-ssh-copy-id.patch
  net-misc/openssh/files/openssh-8.4_p1-hpn-14.22-X509-glue.patch
  net-misc/openssh/files/openssh-8.4_p1-hpn-14.22-glue.patch
  net-misc/openssh/files/openssh-8.4_p1-hpn-14.22-sctp-glue.patch
  net-misc/openssh/files/openssh-8.5_p1-GSSAPI-dns.patch
  net-misc/openssh/files/openssh-8.5_p1-X509-glue-13.0.1.patch
  net-misc/openssh/files/openssh-8.5_p1-hpn-15.1-X509-glue.patch
  net-misc/openssh/files/openssh-8.5_p1-hpn-15.1-glue.patch
  net-misc/openssh/files/openssh-8.5_p1-hpn-15.1-sctp-glue.patch
  net-misc/openssh/files/openssh-8.5_p1-hpn-15.2-glue.patch
  net-misc/openssh/files/openssh-8.6_p1-X509-glue-13.1.patch
  net-misc/openssh/files/openssh-8.6_p1-hpn-15.2-X509-glue.patch
  net-misc/openssh/files/openssh-8.7_p1-GSSAPI-dns.patch
  net-misc/openssh/files/openssh-8.7_p1-X509-glue-13.2.patch
  net-misc/openssh/files/openssh-8.7_p1-hpn-15.2-X509-glue.patch
  net-misc/openssh/files/openssh-8.7_p1-hpn-15.2-glue.patch
  net-misc/openssh/files/sshd-r2.initd
  net-misc/openssh/openssh-8.4_p1-r3.ebuild
  net-misc/openssh/openssh-8.5_p1-r1.ebuild
  net-misc/openssh/openssh-8.5_p1.ebuild
  net-misc/openssh/openssh-8.7_p1-r1.ebuild
  profiles/coreos/base/package.accept_keywords
Labels: main

#1253 *: delete unnecessary packages 2021-09-03
  coreos-base/coreos-dev/coreos-dev-0.1.0.ebuild
  coreos-base/coreos-experimental/coreos-experimental-0.0.1-r5.ebuild
  coreos-base/coreos-experimental/coreos-experimental-0.0.1.ebuild
  coreos-base/coreos-experimental/metadata.xml
  dev-util/lcov/Manifest
  dev-util/lcov/files/geninfo-gcov_4.6_compat.patch
  dev-util/lcov/lcov-1.9.ebuild
  dev-util/lcov/metadata.xml
  sys-apps/systemd-sysv-utils/ChangeLog
  sys-apps/systemd-sysv-utils/Manifest
  sys-apps/systemd-sysv-utils/metadata.xml
  sys-apps/systemd-sysv-utils/systemd-sysv-utils-207-r3.ebuild
Labels: main

#1304 dev-lang/go,*: update Go to 1.17.1
  .github/workflows/go-apply-patch.sh
  .github/workflows/go-releases-main.yml
  app-emulation/containerd/containerd-9999.ebuild
  app-emulation/docker-cli/docker-cli-20.10.8.ebuild
  app-emulation/docker-proxy/docker-proxy-9999.ebuild
  app-emulation/docker-runc/docker-runc-1.0.2.ebuild
  app-emulation/docker/docker-20.10.8.ebuild
  coreos-base/hard-host-depends/hard-host-depends-0.0.1.ebuild
  dev-lang/go/Manifest
  dev-lang/go/go-1.16.8.ebuild
  dev-lang/go/go-1.17.1.ebuild
  eclass/coreos-go-depend.eclass
  eclass/coreos-go-utils.eclass
  eclass/coreos-go.eclass
Labels: main

#1310 .github: get correct ebuild file name from old version
  .github/workflows/common.sh
  .github/workflows/containerd-apply-patch.sh
  .github/workflows/docker-apply-patch.sh
  .github/workflows/firmware-apply-patch.sh
  .github/workflows/go-apply-patch.sh
  .github/workflows/runc-apply-patch.sh
  .github/workflows/rust-apply-patch.sh
Labels: bug, github-actions

#1312 app-crypt/gnupg: update to 2.2.29
  app-crypt/gnupg/Manifest
  app-crypt/gnupg/gnupg-2.2.29.ebuild
  app-crypt/gnupg/metadata.xml
  profiles/coreos/base/package.accept_keywords
Labels: main

#1314 sys-process/audit: fix hash of patch 017e6c6ab95d
  sys-process/audit/Manifest
Labels: bug, alpha, stable, beta, main, lts

#1315 coreos-base/afterburn: bump commit ID
  coreos-base/afterburn/Manifest
  coreos-base/afterburn/afterburn-9999.ebuild
Labels: main

#1316 upgraded libgcrypt to 1.9.4
  profiles/coreos/base/package.accept_keywords
Labels: main
