Repository flatcar/coreos-overlay, pull requests merged in 2021-07, with the labels that each got.

#1089 coreos-base/update_engine: bump commit ID
  coreos-base/update_engine/update_engine-9999.ebuild
Labels: channel/alpha, main

#1088 profiles,app-crypt: fixes needed by libpcre 8.44
  app-crypt/mit-krb5/Manifest
  app-crypt/mit-krb5/files/CVE-2020-28196.patch
  app-crypt/mit-krb5/files/kpropd.xinetd
  app-crypt/mit-krb5/files/mit-krb5-1.12_warn_cflags.patch
  app-crypt/mit-krb5/files/mit-krb5-1.18.2-autoconf-2.70.patch
  app-crypt/mit-krb5/files/mit-krb5-1.18.2-krb5-config.patch
  app-crypt/mit-krb5/files/mit-krb5-config_LDFLAGS-r1.patch
  app-crypt/mit-krb5/files/mit-krb5-warn-crossbuild.patch
  app-crypt/mit-krb5/files/mit-krb5_dont_create_run.patch
  app-crypt/mit-krb5/files/mit-krb5_dont_create_rundir.patch
  app-crypt/mit-krb5/files/mit-krb5kadmind.confd
  app-crypt/mit-krb5/files/mit-krb5kadmind.initd-r2
  app-crypt/mit-krb5/files/mit-krb5kadmind.service
  app-crypt/mit-krb5/files/mit-krb5kdc.confd
  app-crypt/mit-krb5/files/mit-krb5kdc.initd-r2
  app-crypt/mit-krb5/files/mit-krb5kdc.service
  app-crypt/mit-krb5/files/mit-krb5kpropd.confd
  app-crypt/mit-krb5/files/mit-krb5kpropd.initd-r2
  app-crypt/mit-krb5/files/mit-krb5kpropd.service
  app-crypt/mit-krb5/files/mit-krb5kpropd.socket
  app-crypt/mit-krb5/files/mit-krb5kpropd_at.service
  app-crypt/mit-krb5/metadata.xml
  app-crypt/mit-krb5/mit-krb5-1.18.2-r4.ebuild
Labels: alpha, main

#1092 app-admin/updateservicectl: sync with current main - 2021-07-05
  app-admin/updateservicectl/updateservicectl-9999.ebuild
Labels: alpha, main

#1093 profiles: accept ~amd64 & ~arm64 for libgcrypt-1.9.3
  profiles/coreos/base/package.accept_keywords
Labels: channel/alpha, main

#929 Enable MDIO_BCM_UNIMAC for arm64
  sys-kernel/coreos-modules/files/arm64_defconfig-5.10
Labels: bug, channel/alpha, main

#932 profiles: force to use ssl USE flag for wget
  profiles/coreos/arm64/package.use.force
  profiles/coreos/base/package.use.force
Labels: alpha, main

#1113 app-emulation/open-vm-tools: update to 11.3.0
  app-emulation/open-vm-tools/Manifest
  app-emulation/open-vm-tools/files/open-vm-tools-11.3.0-0001-configure-Add-options-for-fuse-hgfs-and-udev.patch
  app-emulation/open-vm-tools/open-vm-tools-11.3.0.ebuild
  coreos-base/oem-vmware/oem-vmware-11.3.0.ebuild
Labels: alpha, main

#1120 app-emulation/containerd: update to 1.5.4
  app-emulation/containerd/Manifest
  app-emulation/containerd/containerd-1.5.4.ebuild
  app-emulation/containerd/containerd-9999.ebuild
  app-torcx/docker/docker-19.03.ebuild
Labels: alpha, beta, flatcar-2905, flatcar-2920, main, stable

#1126 sys-apps/systemd: Bump to v247.7
  sys-apps/systemd/Manifest
  sys-apps/systemd/systemd-247.7.ebuild
Labels: channel/alpha, main
