Repository flatcar/coreos-overlay, pull requests merged in 2021-12, with the labels that each got.

#1453 sys-apps/ignition: update golang.org/x/text to 0.3.7
  changelog/security/2021-11-30-CVE-2020-14040.md
  sys-apps/ignition/ignition-9999.ebuild
Labels: main

#1455 profiles: adjust profiles for vim 8.2.3582
  profiles/coreos/amd64/generic/package.use
  profiles/coreos/arm64/generic/package.use
  profiles/coreos/base/package.accept_keywords
Labels: main

#1462 Teach github actions to generate changelog entries
  .github/workflows/cacerts-apply-patch.sh
  .github/workflows/common.sh
  .github/workflows/containerd-apply-patch.sh
  .github/workflows/docker-apply-patch.sh
  .github/workflows/firmware-apply-patch.sh
  .github/workflows/go-apply-patch.sh
  .github/workflows/kernel-apply-patch.sh
  .github/workflows/runc-apply-patch.sh
  .github/workflows/rust-apply-patch.sh
  .github/workflows/vmware-apply-patch.sh
Labels: github-actions

#1472 dev-lang/go: update Go to 1.16.11
  changelog/updates/2021-12-03-golang-update.md
  dev-lang/go/Manifest
  dev-lang/go/go-1.16.11.ebuild
Labels: stable, flatcar-2983

#1473 app-arch/torcx: update golang.org/x/{crypto,text}
  app-arch/torcx/torcx-0.2.0-r5.ebuild
  app-arch/torcx/torcx-9999.ebuild
  changelog/security/2021-12-03-torcx-golang-crypto-text.md
Labels: main

#1469 app-emulation/qemu: update to 6.1.0
  app-emulation/qemu/Manifest
  app-emulation/qemu/files/65-kvm.rules-r1
  app-emulation/qemu/files/qemu-5.2.0-cleaner-werror.patch
  app-emulation/qemu/files/qemu-5.2.0-fix-firmware-path.patch
  app-emulation/qemu/files/qemu-5.2.0-no-pie-ld.patch
  app-emulation/qemu/files/qemu-5.2.0-strings.patch
  app-emulation/qemu/files/qemu-6.0.0-make.patch
  app-emulation/qemu/files/qemu-6.1.0-automagic-libbpf.patch
  app-emulation/qemu/files/qemu-6.1.0-strings.patch
  app-emulation/qemu/files/qemu-9999-fix-firmware-path.patch
  app-emulation/qemu/metadata.xml
  app-emulation/qemu/qemu-6.1.0-r1.ebuild
  changelog/security/2021-12-02-qemu-6.1.md
  changelog/updates/2021-12-02-qemu-6.1.md
  profiles/coreos/arm64/package.accept_keywords
  profiles/coreos/base/package.accept_keywords
  profiles/coreos/base/package.use
Labels: main

#1234 dev-vcs/repo: update to 2.8 for python3 (lts)
  changelog/updates/2021-12-06-repo-2.8.md
  dev-vcs/repo/Manifest
  dev-vcs/repo/files/repo-1.25
  dev-vcs/repo/repo-1.25.ebuild
  dev-vcs/repo/repo-2.8.ebuild
Labels: lts

#1474 coreos-devel/mantle: update to 0.17.0-r1 for golang.org/x/{crypto,text}
  changelog/security/2021-12-03-mantle-golang-crypto-text.md
  changelog/updates/2021-12-03-mantle-update.md
  coreos-devel/mantle/mantle-0.17.0-r1.ebuild
  coreos-devel/mantle/mantle-9999.ebuild
Labels: main

#1485 changelog: add missing CVE for golang.org/x/text in ignition
  changelog/security/2021-11-30-golang-text-ignition.md
Labels: main

#1344 net-misc/openssh: Sync with Gentoo upstream; updates to openssh 8.8_p1
  changelog/security/2021-12-09-openssh-8.8.md
  changelog/updates/2021-12-09-openssh-8.8.md
  coreos-base/coreos-init/coreos-init-0.0.1-r172.ebuild
  coreos-base/coreos-init/coreos-init-9999.ebuild
  net-misc/openssh/Manifest
  net-misc/openssh/files/openssh-8.7_p1-X509-glue-13.2.patch
  net-misc/openssh/files/openssh-8.8_p1-X509-glue-13.2.3.patch
  net-misc/openssh/metadata.xml
  net-misc/openssh/openssh-8.8_p1-r3.ebuild
  profiles/coreos/base/package.accept_keywords
Labels: main

#1493 profiles: adjust profiles for vim 8.2.3582 for flatcar-3033,3066
  profiles/coreos/amd64/generic/package.use
  profiles/coreos/arm64/generic/package.use
  profiles/coreos/base/package.accept_keywords
Labels: bug, alpha, beta

#1495 sys-auth/google-oslogin: accept ssh-rsa in sshd_config for openssh 8.8
  sys-auth/google-oslogin/files/sshd_config
  sys-auth/google-oslogin/google-oslogin-20200910.00-r1.ebuild
Labels: bug, alpha, main, flatcar-3087

#1484 .github/wf: add mirror-calico action
  .github/workflows/mirror-calico.sh
  .github/workflows/mirror-calico.yml
  .github/workflows/mirror-to-ghcr.sh
Labels: github-actions

#1254 sys-apps/portage: update to 3.0.28-r1 for EAPI 8
  profiles/coreos/base/make.defaults
  sys-apps/portage/Manifest
  sys-apps/portage/README.md
  sys-apps/portage/metadata.xml
  sys-apps/portage/portage-3.0.28-r1.ebuild
Labels: main

#1517 sys-kernel/bootengine: make dracut install loop driver
  sys-kernel/bootengine/bootengine-0.0.38-r12.ebuild
  sys-kernel/bootengine/bootengine-9999.ebuild
Labels: bug, alpha, main, flatcar-3087
