Repository flatcar/coreos-overlay, pull requests merged in 2022-06, with the labels that each got.

#1916 sys-apps/ignition: upgrade to 2.14.0
  changelog/updates/2022-05-25-ignition.md
  sys-apps/ignition/files/0001-sed-s-coreos-flatcar-linux.patch
  sys-apps/ignition/files/0002-mod-add-ign-converter-dependency.patch
  sys-apps/ignition/files/0003-sum-go-mod-tidy.patch
  sys-apps/ignition/files/0004-vendor-go-mod-vendor.patch
  sys-apps/ignition/files/0005-config-v3_4-convert-ignition-2.x-to-3.4-exp.patch
  sys-apps/ignition/files/0006-internal-prv-cmdline-backport-flatcar-patch.patch
  sys-apps/ignition/files/0007-provider-qemu-apply-fw_cfg-patch.patch
  sys-apps/ignition/files/0008-config-3_4-test-add-ignition-2.x-test-cases.patch
  sys-apps/ignition/files/0009-internal-disk-fs-ignore-fs-format-mismatches-for-the.patch
  sys-apps/ignition/files/0010-VMware-Fix-guestinfo.-.config.data-and-.config.url-v.patch
  sys-apps/ignition/files/0011-config-version-handle-configuration-version-1.patch
  sys-apps/ignition/files/0012-config-util-add-cloud-init-detection-to-initial-pars.patch
  sys-apps/ignition/files/0013-Revert-drop-OEM-URI-support.patch
  sys-apps/ignition/files/0014-internal-resource-url-support-btrfs-as-OEM-partition.patch
  sys-apps/ignition/files/0015-internal-exec-stages-disks-prevent-races-with-udev.patch
  sys-apps/ignition/files/0016-update-ign-converter-to-fix-link-translation.patch
  sys-apps/ignition/files/0017-mod-update-ign-converter.patch
  sys-apps/ignition/ignition-2.14.0-r1.ebuild
  sys-apps/ignition/ignition-9999.ebuild
Labels: main

#1945 profiles: delete libxml2 keywords
  profiles/coreos/base/package.accept_keywords
Labels: main

#1956 Init bump
  changelog/changes/2022-06-12-uefibootentry.md
  coreos-base/coreos-init/coreos-init-9999.ebuild
Labels: main

#1973 sys-firmware/intel-microcode: Sync with Gentoo upstream; updates to intel-microcode-20220510_p20220508
  changelog/security/2022-06-17-intel-microcode-20220510_p20220508.md
  changelog/updates/2022-06-17-intel-microcode-20220510_p20220508.md
  sys-firmware/intel-microcode/Manifest
  sys-firmware/intel-microcode/intel-microcode-20220510_p20220508.ebuild
Labels: alpha, main

#1965 app-emulation/containerd: update to 1.5.13 for Stable, LTS
  app-emulation/containerd/Manifest
  app-emulation/containerd/containerd-1.5.13.ebuild
  app-emulation/containerd/containerd-9999.ebuild
  app-torcx/docker/docker-20.10.ebuild
  changelog/security/2022-06-13-containerd-1.5.13.md
  changelog/updates/2022-06-13-containerd-1.5.13-update.md
Labels: stable, lts, flatcar-3033, flatcar-3139
