Repository flatcar/coreos-overlay, pull requests merged in 2022-10, with the labels that each got.

#2189 Profiles and environment overrides for packages refresh
  coreos/config/env/net-misc/curl
  profiles/coreos/base/package.accept_keywords
  profiles/coreos/base/package.unmask
Labels: main

#2198 coreos-base/coreos-init: Bring in the port customization changes
  changelog/changes/2022-10-04-flatcar-update-new-flags.md
  coreos-base/coreos-init/coreos-init-0.0.1-r176.ebuild
  coreos-base/coreos-init/coreos-init-9999.ebuild
Labels: main

#2180 Development utilities update
  coreos-base/hard-host-depends/hard-host-depends-0.0.1-r205.ebuild
  coreos-base/hard-host-depends/hard-host-depends-0.0.1.ebuild
  coreos/config/cross_compile_config.cmake
  coreos/config/env/dev-util/cmake
  coreos/config/env/dev-util/dialog
  dev-util/bsdiff/Manifest
  dev-util/bsdiff/bsdiff-4.3-r4.ebuild
  dev-util/bsdiff/metadata.xml
  profiles/coreos/arm64/package.accept_keywords
  profiles/coreos/base/package.accept_keywords
  profiles/coreos/base/package.use
  profiles/coreos/targets/generic/package.provided
  profiles/coreos/targets/generic/package.use
Labels: main

#2214 motd: Update the motd to notify about the deprecating LTS-2021
  coreos-base/coreos-init/coreos-init-9999.ebuild
Labels: lts

#2215 motd: Update the motd to notify about the deprecating LTS-2021
  coreos-base/coreos-init/coreos-init-9999.ebuild
Labels: lts

#2211 sys-apps/dbus: Update to 1.14.4
  changelog/security/2022-10-11-dbus-update.md
  changelog/updates/2022-10-11-dbus-update.md
  sys-apps/dbus/Manifest
  sys-apps/dbus/README.md
  sys-apps/dbus/dbus-1.14.4.ebuild
  sys-apps/dbus/files/80-dbus-r1
  sys-apps/dbus/files/dbus-1.12.22-check-fd.patch
  sys-apps/dbus/files/dbus-1.14.0-oom_score_adj.patch
Labels: main

#2212 app-admin/logrotate: Update to 3.20.1
  app-admin/logrotate/Manifest
  app-admin/logrotate/files/logrotate-3.20.1-log-changes.patch
  app-admin/logrotate/files/logrotate.conf
  app-admin/logrotate/logrotate-3.20.1-r1.ebuild
  app-admin/logrotate/metadata.xml
  changelog/security/2022-10-11-logrotate-update.md
  changelog/updates/2022-10-11-logrotate-update.md
Labels: main

#2209 Profile changes for weekly package updates
  profiles/coreos/arm64/package.accept_keywords
  profiles/coreos/base/package.accept_keywords
  profiles/coreos/base/package.use
Labels: main

#2221 github: Deduplicate kernel and ca-certificates workflows
  .github/workflows/cacerts-apply-patch.sh
  .github/workflows/cacerts-release.yml
  .github/workflows/cacerts-releases-alpha.yml
  .github/workflows/cacerts-releases-beta.yml
  .github/workflows/cacerts-releases-lts-2021.yml
  .github/workflows/cacerts-releases-lts.yml
  .github/workflows/cacerts-releases-main.yaml
  .github/workflows/cacerts-releases-stable.yml
  .github/workflows/common.sh
  .github/workflows/figure-out-branch.sh
  .github/workflows/kernel-apply-patch.sh
  .github/workflows/kernel-release.yml
  .github/workflows/kernel-releases-alpha.yml
  .github/workflows/kernel-releases-beta.yml
  .github/workflows/kernel-releases-lts-2021.yml
  .github/workflows/kernel-releases-lts.yml
  .github/workflows/kernel-releases-main.yml
  .github/workflows/kernel-releases-stable.yml
Labels: github-actions

#2241 Profile changes for the weekly updates
  profiles/coreos/amd64/sdk/package.accept_keywords
  profiles/coreos/base/package.accept_keywords
Labels: main

#2243 profiles: Accept keywords for curl 7.85
  changelog/security/2022-10-20-curl-update.md
  changelog/updates/2022-10-20-curl-update.md
  profiles/coreos/base/package.accept_keywords
  profiles/coreos/base/package.use
Labels: main

#2210 app-editors/vim: Move back to portage-stable
  app-editors/vim-core/Manifest
  app-editors/vim-core/files/gvim.svg
  app-editors/vim-core/files/vimrc-r6
  app-editors/vim-core/files/xxd-completion
  app-editors/vim-core/metadata.xml
  app-editors/vim-core/vim-core-9.0.0469.ebuild
  app-editors/vim/Manifest
  app-editors/vim/files/vim-completion
  app-editors/vim/metadata.xml
  app-editors/vim/vim-9.0.0469.ebuild
  profiles/coreos/base/package.accept_keywords
Labels: main

#2246 coreos-base/oem-ec2-compat: pull ssh keys from metadata server
  changelog/changes/2022-10-19-openstack-metadata.md
  coreos-base/oem-ec2-compat/files/base/openstack.ign
  coreos-base/oem-ec2-compat/oem-ec2-compat-0.1.2-r2.ebuild
Labels: main

#2235 sys-kernel: enable IOMMU on arm64
  changelog/bugfixes/2022-10-17-iommu-arm64.md
  sys-kernel/coreos-modules/files/arm64_defconfig-5.15
Labels: main

#2239 arm64 kernel shrink
  changelog/changes/2022-10-24-kernel-options.md
  sys-kernel/coreos-modules/files/arm64_defconfig-5.15
  sys-kernel/coreos-modules/files/commonconfig-5.15
Labels: main

#2240 coreos: add qemu-guest-agent to images
  coreos-base/coreos/coreos-0.0.1-r304.ebuild
  coreos-base/coreos/coreos-0.0.1.ebuild
Labels: main

#2248 Profile additions and cleanups for weekly update
  profiles/coreos/amd64/sdk/package.accept_keywords
  profiles/coreos/arm64/package.accept_keywords
  profiles/coreos/base/package.accept_keywords
  profiles/coreos/base/package.unmask
Labels: main
