Repository flatcar/coreos-overlay, pull requests merged in 2022-01, with the labels that each got.

#1413 profiles: Changes related to package updates in portage-stable (getting rid of EAPI 4)
  profiles/coreos/arm64/package.accept_keywords
  profiles/coreos/targets/generic/package.use
Labels: main

#1565 sys-apps/policycoreutils: fix policy root path
  changelog/bugfixes/2022-01-13-policycoreutils-fix-root-path.md
  sys-apps/policycoreutils/policycoreutils-3.1-r3.ebuild
Labels: alpha

#1596 sys-libs/glibc: update to 2.33-r10
  changelog/security/2022-01-28-glibc-2.33-r10.md
  sys-libs/glibc/Manifest
  sys-libs/glibc/glibc-2.33-r10.ebuild
  sys-libs/glibc/metadata.xml
Labels: alpha, stable, beta, main
