Repository flatcar/coreos-overlay, pull requests merged in 2022-09, with the labels that each got.

#2129 app-emulation/containerd: fix checksums of containerd 1.5.13
  app-emulation/containerd/Manifest
Labels: bug, lts

#2131 app-emulation/containerd: revert containerd 1.5.13 checksum
  app-emulation/containerd/Manifest
Labels: bug, lts

#2130 sys-auth/polkit: Update to 121
  changelog/security/2022-09-06-polkit.md
  changelog/updates/2022-09-06-polkit.md
  profiles/coreos/base/package.accept_keywords
  sys-auth/polkit/Manifest
  sys-auth/polkit/files/97_Add_duktape_as_javascript_engine.patch
  sys-auth/polkit/files/polkit-0.120-CVE-2021-4034.patch
  sys-auth/polkit/files/polkit-0.120-meson.patch
  sys-auth/polkit/files/polkit-0.120_p20220509-make-netgroup-support-optional.patch
  sys-auth/polkit/metadata.xml
  sys-auth/polkit/polkit-121.ebuild
Labels: main

#2137 profiles: accept keywords and clean up for rsync 3.2.6
  profiles/coreos/base/package.accept_keywords
  profiles/coreos/base/package.use
Labels: main

#2135 emerge-gitclone: update workon_commit ref to latest commit
  changelog/changes/2022-09-08-emerge-gitclone.md
  coreos-base/emerge-gitclone/emerge-gitclone-9999.ebuild
Labels: main

#2136 .github: migrate to SDK container based Github Actions
  .github/workflows/cacerts-apply-patch.sh
  .github/workflows/cacerts-releases-alpha.yml
  .github/workflows/cacerts-releases-beta.yml
  .github/workflows/cacerts-releases-lts-2021.yml
  .github/workflows/cacerts-releases-lts.yml
  .github/workflows/cacerts-releases-main.yaml
  .github/workflows/cacerts-releases-stable.yml
  .github/workflows/common.sh
  .github/workflows/containerd-apply-patch.sh
  .github/workflows/containerd-releases-main.yml
  .github/workflows/docker-apply-patch.sh
  .github/workflows/docker-releases-main.yml
  .github/workflows/firmware-apply-patch.sh
  .github/workflows/firmware-releases-main.yml
  .github/workflows/go-apply-patch.sh
  .github/workflows/go-releases-main.yml
  .github/workflows/kernel-apply-patch.sh
  .github/workflows/kernel-releases-alpha.yml
  .github/workflows/kernel-releases-beta.yml
  .github/workflows/kernel-releases-lts-2021.yml
  .github/workflows/kernel-releases-lts.yml
  .github/workflows/kernel-releases-main.yml
  .github/workflows/kernel-releases-stable.yml
  .github/workflows/runc-apply-patch.sh
  .github/workflows/runc-releases-main.yml
  .github/workflows/rust-apply-patch.sh
  .github/workflows/rust-release-main.yml
  .github/workflows/setup-flatcar-sdk.sh
  .github/workflows/vmware-apply-patch.sh
  .github/workflows/vmware-releases-main.yml
Labels: github-actions

#2139 coreos-base/coreos: add sys-devel/gettext
  changelog/bugfixes/2022-09-13-gettext.md
  changelog/updates/2022-09-13-gettext.md
  coreos-base/coreos/coreos-0.0.1.ebuild
Labels: bug, alpha, stable, beta, main

#2141 profiles: Add accept keywords for updated libxml2
  profiles/coreos/base/package.accept_keywords
Labels: main

#2152 sys-apps/ignition: Use renamed package name
  sys-apps/ignition/ignition-9999.ebuild
Labels: lts

#2154 app-admin/locksmith: bump commit ID
  app-admin/locksmith/locksmith-0.7.0.ebuild
  app-admin/locksmith/locksmith-9999.ebuild
  changelog/updates/2022-09-14-locksmith.md
Labels: alpha, stable, beta, main, flatcar-3033

#2158 .github: fix Go changelog and git show-ref bug
  .github/workflows/common.sh
  .github/workflows/go-apply-patch.sh
Labels: github-actions

#2166 coreos-base/emerge-gitclone: Bring in a fix for developer channel
  coreos-base/emerge-gitclone/emerge-gitclone-0.0.1-r590.ebuild
  coreos-base/emerge-gitclone/emerge-gitclone-9999.ebuild
Labels: alpha, stable, beta, main, lts

#2187 sys-apps/ignition: rework ignition patches
  changelog/bugfixes/2022-09-27-ignition.md
  sys-apps/ignition/files/0001-sed-s-coreos-flatcar.patch
  sys-apps/ignition/files/0002-mod-add-flatcar-ignition-0.36.2.patch
  sys-apps/ignition/files/0002-mod-add-ign-converter-dependency.patch
  sys-apps/ignition/files/0003-sum-go-mod-tidy.patch
  sys-apps/ignition/files/0004-vendor-go-mod-vendor.patch
  sys-apps/ignition/files/0005-config-add-ignition-translation.patch
  sys-apps/ignition/files/0006-config-v3_4-convert-ignition-2.x-to-3.4-exp.patch
  sys-apps/ignition/files/0007-internal-prv-cmdline-backport-flatcar-patch.patch
  sys-apps/ignition/files/0008-provider-qemu-apply-fw_cfg-patch.patch
  sys-apps/ignition/files/0009-config-3_4-test-add-ignition-2.x-test-cases.patch
  sys-apps/ignition/files/0010-internal-disk-fs-ignore-fs-format-mismatches-for-the.patch
  sys-apps/ignition/files/0011-VMware-Fix-guestinfo.-.config.data-and-.config.url-v.patch
  sys-apps/ignition/files/0012-config-version-handle-configuration-version-1.patch
  sys-apps/ignition/files/0013-config-util-add-cloud-init-detection-to-initial-pars.patch
  sys-apps/ignition/files/0014-Revert-drop-OEM-URI-support.patch
  sys-apps/ignition/files/0015-internal-resource-url-support-btrfs-as-OEM-partition.patch
  sys-apps/ignition/files/0016-internal-exec-stages-disks-prevent-races-with-udev.patch
  sys-apps/ignition/files/0016-mod-bump-ign-converter-to-pull-networkd-fix.patch
  sys-apps/ignition/files/README.md
  sys-apps/ignition/ignition-2.14.0-r4.ebuild
  sys-apps/ignition/ignition-9999.ebuild
Labels: alpha, stable, beta, main

#2134 coreos-base/gmerge: Bump package to bring emerge-gitclone backport
  coreos-base/gmerge/gmerge-0.0.1-r584.ebuild
  coreos-base/gmerge/gmerge-9999.ebuild
Labels: lts

#2140 Update vim to v9.0.0469
  app-editors/vim-core/Manifest
  app-editors/vim-core/files/gvim.svg
  app-editors/vim-core/files/vimrc-r6
  app-editors/vim-core/files/xxd-completion
  app-editors/vim-core/metadata.xml
  app-editors/vim-core/vim-core-9.0.0469.ebuild
  app-editors/vim/Manifest
  app-editors/vim/files/vim-completion
  app-editors/vim/metadata.xml
  app-editors/vim/vim-9.0.0469.ebuild
  changelog/security/2022-09-20-vim-update.md
  changelog/updates/2022-09-20-vim-update.md
  profiles/coreos/amd64/generic/package.use
  profiles/coreos/arm64/generic/package.use
  profiles/coreos/base/package.accept_keywords
  profiles/coreos/targets/generic/package.use
Labels: main
