Repository flatcar/coreos-overlay, pull requests merged in 2022-11, with the labels that each got.

#2265 profiles: accept keywords for multipath-tools 0.9.3
  profiles/coreos/base/package.accept_keywords
Labels: main

#2238 github: Modernize the actions a bit
  .github/workflows/containerd-apply-patch.sh
  .github/workflows/containerd-releases-main.yml
  .github/workflows/docker-apply-patch.sh
  .github/workflows/docker-releases-main.yml
  .github/workflows/firmware-apply-patch.sh
  .github/workflows/firmware-releases-main.yml
  .github/workflows/go-apply-patch.sh
  .github/workflows/go-releases-main.yml
  .github/workflows/mirror-calico.yml
  .github/workflows/runc-apply-patch.sh
  .github/workflows/runc-releases-main.yml
  .github/workflows/rust-apply-patch.sh
  .github/workflows/rust-release-main.yml
  .github/workflows/setup-flatcar-sdk.sh
  .github/workflows/vmware-apply-patch.sh
  .github/workflows/vmware-releases-main.yml
Labels: github-actions

#2222 sys-libs/glibc: Update to 2.35
  changelog/updates/2022-10-14-update-glibc.md
  sys-libs/glibc/Manifest
  sys-libs/glibc/glibc-2.35-r8.ebuild
Labels: main

#2267 dev-libs/openssl: Bump to 3.0.7
  changelog/updates/2022-11-03-openssl-update.md
  dev-libs/openssl/Manifest
  dev-libs/openssl/files/0001-openssl.patch
  dev-libs/openssl/metadata.xml
  dev-libs/openssl/openssl-3.0.7.ebuild
Labels: main

#2269 dev-lang/go: add 1.19.3, update 1.18.8, remove 1.17
  .github/workflows/go-apply-patch.sh
  .github/workflows/go-releases-main.yml
  changelog/updates/2022-11-03-go-1.19.3-update.md
  coreos-base/hard-host-depends/hard-host-depends-0.0.1.ebuild
  dev-lang/go/Manifest
  dev-lang/go/go-1.18.8.ebuild
  dev-lang/go/go-1.19.3.ebuild
  eclass/coreos-go-depend.eclass
  eclass/coreos-go-lang.eclass
  eclass/coreos-go.eclass
Labels: main

#2266 Profile cleanups for weekly package updates
  profiles/coreos/amd64/sdk/package.accept_keywords
  profiles/coreos/base/package.accept_keywords
  sys-devel/sysroot-wrappers/Manifest
  sys-devel/sysroot-wrappers/sysroot-wrappers-0.1.ebuild
  sys-devel/sysroot-wrappers/sysroot-wrappers-0.2.ebuild
Labels: main

#2277 sys-apps/ignition: fix OEM detection
  changelog/bugfixes/2022-11-10-ignition.md
  sys-apps/ignition/files/0017-translation-support-OEM-and-oem.patch
  sys-apps/ignition/ignition-2.14.0-r5.ebuild
  sys-apps/ignition/ignition-9999.ebuild
Labels: alpha, beta, main

#2288 profiles: Cleanups for weekly package updates
  profiles/coreos/base/package.accept_keywords
  profiles/coreos/targets/generic/package.provided
  profiles/coreos/targets/sdk/package.use
Labels: main

#2298 profiles: Updates for weekly package updates
  profiles/coreos/base/package.accept_keywords
Labels: main

#2299 profiles: accept keywords for app-arch/cpio 2.13-r3
  profiles/coreos/base/package.accept_keywords
Labels: main
