Repository flatcar/coreos-overlay, pull requests merged in 2022-05, with the labels that each got.

#1859 .github: add cacerts/kernel actions for current LTS
  .github/workflows/cacerts-releases-lts.yml
  .github/workflows/kernel-releases-lts.yml
Labels: github-actions

#1860 profiles: accept keywords for git 2.35.3
  profiles/coreos/base/package.accept_keywords
Labels: main

#1861 profiles: accept keywords for net-misc/rsync
  profiles/coreos/base/package.accept_keywords
Labels: main

#1866 app-arch/torcx: update golang.org/x/crypto
  app-arch/torcx/torcx-0.2.0-r6.ebuild
  app-arch/torcx/torcx-9999.ebuild
  changelog/security/2022-05-06-torcx-golang-crypto.md
Labels: main

#1838 profiles: add keywords to cross-*/binutils as well
  profiles/coreos/base/package.accept_keywords
Labels: main

#1881 dev-lang/go: update to 1.17.10 for flatcar-3227
  changelog/security/2022-05-11-go-1.17.10.md
  changelog/updates/2022-05-11-golang-1.17.10-update.md
  dev-lang/go/Manifest
  dev-lang/go/go-1.17.10.ebuild
Labels: stable, beta, flatcar-3139, flatcar-3227

#1819 Package updates, 2021 edition, part 1 - fallout fixes from the update of profiles in portage-stable
  changelog/updates/2022-05-12-dbus-and-samba-update.md
  coreos/config/env/net-nds/openldap
  coreos/config/env/sys-libs/e2fsprogs-libs
  net-fs/samba/Manifest
  net-fs/samba/files/samba-4.11-fix-glibc-2.32-function-collisions.patch
  net-fs/samba/files/samba-4.13-vfs_snapper_configure_option.patch
  net-fs/samba/files/samba-4.13-winexe_option.patch
  net-fs/samba/files/samba-4.9.2-timespec.patch
  net-fs/samba/metadata.xml
  net-fs/samba/samba-4.15.4-r3.ebuild
  profiles/coreos/base/package.accept_keywords
  profiles/coreos/base/package.unmask
  profiles/coreos/base/package.use
  profiles/coreos/base/package.use.mask
  profiles/coreos/targets/generic/make.defaults
  profiles/coreos/targets/sdk/package.use
  sys-apps/dbus/Manifest
  sys-apps/dbus/README.md
  sys-apps/dbus/dbus-1.12.22-r1.ebuild
  sys-apps/dbus/files/dbus-1.12.22-check-fd.patch
  sys-apps/dbus/files/dbus-1.14.0-oom_score_adj.patch
  sys-apps/dbus/metadata.xml
  sys-libs/ldb/Manifest
  sys-libs/ldb/README.md
  sys-libs/ldb/files/ldb-1.1.31-fix_PKGCONFIGDIR-when-python-disabled.patch
  sys-libs/ldb/files/ldb-1.5.2-optional_packages.patch
  sys-libs/ldb/ldb-2.3.0-r2.ebuild
  sys-libs/ldb/metadata.xml
Labels: main

#1898 dev-libs/openssl: update to 3.0.3
  changelog/security/2022-05-17-openssl-3.0.3.md
  changelog/updates/2022-05-17-openssl-3.0.3.md
  dev-libs/openssl/Manifest
  dev-libs/openssl/files/gentoo.config-1.0.2
  dev-libs/openssl/metadata.xml
  dev-libs/openssl/openssl-3.0.3.ebuild
Labels: main

#1899 sys-libs/ncurses: update to 6.3_p20220423
  changelog/security/2022-05-17-ncurses-6.3_p20220423.md
  changelog/updates/2022-05-17-ncurses-6.3_p20220423.md
  sys-libs/ncurses/Manifest
  sys-libs/ncurses/ncurses-6.3_p20220423.ebuild
Labels: main

#1901 profiles: accept keywords ~arm64 for curl 7.83.1
  profiles/coreos/arm64/package.accept_keywords
Labels: main

#1908 x11-drivers/nvidia-{drivers,metadata}: update to 510.73.05
  changelog/security/2022-05-19-nvidia-drivers-510.73.05.md
  changelog/updates/2022-05-19-nvidia-drivers-510.73.05.md
  x11-drivers/nvidia-drivers/nvidia-drivers-510.73.05.ebuild
  x11-drivers/nvidia-metadata/files/nvidia-metadata
  x11-drivers/nvidia-metadata/nvidia-metadata-510.73.05.ebuild
Labels: beta, main, flatcar-3227

#1848 sys-kernel/bootengine: pull network kargs
  changelog/changes/2022-05-12-bootengine.md
  sys-kernel/bootengine/bootengine-9999.ebuild
Labels: main

#1912 coreos-base/oem-gce: bring back shutdown scripts
  changelog/bugfixes/2022-05-23-gcp-shutdown.md
  coreos-base/oem-gce/files/units/oem-gce.service
Labels: main

#1911 sys-power/acpid: new package
  coreos-base/coreos/coreos-0.0.1.ebuild
  profiles/coreos/base/make.defaults
  profiles/coreos/base/package.accept_keywords
Labels: main

#1900 Package updates, 2021 edition, part 2 - python update
  changelog/updates/2022-05-23-python-update.md
  coreos-base/hard-host-depends/hard-host-depends-0.0.1.ebuild
  dev-lang/python-oem/Manifest
  dev-lang/python-oem/README.md
  dev-lang/python-oem/python-oem-3.9.12.ebuild
  dev-python/boto/boto-2.49.0-r4.ebuild
  dev-python/boto/files/boto-2.49.0-py310.patch
  dev-python/distro-oem/Manifest
  dev-python/distro-oem/distro-oem-1.7.0.ebuild
  profiles/coreos/base/package.mask
  profiles/coreos/base/package.use
  profiles/coreos/targets/generic/package.use
  profiles/coreos/targets/sdk/package.use
  sec-policy/selinux-base/selinux-base-2.20200818-r2.ebuild
Labels: main
