Repository flatcar/coreos-overlay, pull requests merged in 2022-03, with the labels that each got.

#1683 coreos-base/coreos-init: move processes to root cgroup before unbinding controllers
  coreos-base/coreos-init/coreos-init-0.0.1-r174.ebuild
  coreos-base/coreos-init/coreos-init-9999.ebuild
Labels: alpha, beta

#1648 sys-libs/timezone-data: Sync with Gentoo upstream
  changelog/updates/2022-01-01-timezone-data-2021a-update.md
  sys-libs/timezone-data/Manifest
  sys-libs/timezone-data/metadata.xml
  sys-libs/timezone-data/timezone-data-2019b-r2.ebuild
  sys-libs/timezone-data/timezone-data-2021a-r1.ebuild
Labels: main

#1699 containerd: Enable SELinux labeling support by default
  app-emulation/containerd/files/config.toml
  changelog/changes/2022-03-08-containerd-selinux.md
Labels: main

#1681 Profile cleanups for updated packages from 2017
  profiles/coreos/arm64/package.accept_keywords
  profiles/coreos/base/package.accept_keywords
  profiles/coreos/targets/generic/package.provided
Labels: main

#1711 changelog: add security changelog for Go 1.17.8
  changelog/security/2022-03-11-go-1.17.8.md
Labels: alpha, stable, beta, main

#1722 sys-apps/systemd: update to 249.11 for flatcar-3139
  changelog/security/2022-03-14-systemd-249.11.md
  changelog/updates/2022-03-14-systemd-249.11-update.md
  sys-apps/systemd/Manifest
  sys-apps/systemd/systemd-249.11.ebuild
Labels: stable, beta, flatcar-3033, flatcar-3139

#1688 Profile cleanups for updated packages from 2018
  coreos-base/update_engine/update_engine-0.4.10-r6.ebuild
  coreos-base/update_engine/update_engine-9999.ebuild
  profiles/coreos/arm64/package.accept_keywords
  profiles/coreos/base/package.use
  profiles/coreos/targets/sdk/package.accept_keywords
Labels: main

#1728 dev-libs/openssl: bump to 1.1.1n
  changelog/security/2022-03-16-openssl.md
  changelog/updates/2022-03-16-openssl.md
  dev-libs/openssl/Manifest
  dev-libs/openssl/metadata.xml
  dev-libs/openssl/openssl-1.1.1n.ebuild
  profiles/coreos/base/package.unmask
  profiles/coreos/base/package.use
Labels: stable, flatcar-3033

#1735 sys-libs/pam: Update to 1.5.1_p20210622
  changelog/updates/2022-03-17-pam-1.5.1_p20210622-update.md
  sys-libs/pam/Manifest
  sys-libs/pam/files/pam-1.5.1-musl.patch
  sys-libs/pam/files/tmpfiles.d/pam.conf
  sys-libs/pam/metadata.xml
  sys-libs/pam/pam-1.5.1_p20210622-r1.ebuild
Labels: main

#1744 sys-auth/pambase: update stub version to 20220214
  changelog/updates/2022-03-18-pambase-20220214.md
  sys-auth/pambase/pambase-20220214.ebuild
Labels: main

#1743 sys-firmware/intel-microcode: update to 20220207_p20220207
  changelog/security/2022-03-18-intel-microcode-20220207_p20220207.md
  changelog/updates/2022-03-18-intel-microcode-20220207_p20220207.md
  sys-firmware/intel-microcode/Manifest
  sys-firmware/intel-microcode/intel-microcode-20220207_p20220207.ebuild
  sys-firmware/intel-microcode/metadata.xml
Labels: main

#1747 profiles/base: enable `fips` across the OS
  changelog/changes/2022-03-22-fips.md
  profiles/coreos/base/make.defaults
  profiles/coreos/base/package.accept_keywords
  profiles/coreos/base/package.use
Labels: main

#1745 profiles: disable su USE flag for util-linux
  profiles/coreos/base/package.use
Labels: main

#1759 update containerd to 1.5.11
  app-emulation/containerd/Manifest
  app-emulation/containerd/containerd-1.5.11.ebuild
  app-emulation/containerd/containerd-9999.ebuild
  app-torcx/docker/docker-20.10.ebuild
  changelog/security/2022-03-24-containerd-1.5.11.md
  changelog/updates/2022-03-24-containerd-1.5.11-update.md
Labels: stable, beta, flatcar-3033, flatcar-3139

#1708 Profile cleanups for updated packages from 2019
  coreos-base/afterburn/afterburn-4.0.0-r5.ebuild
  coreos-base/afterburn/afterburn-9999.ebuild
  coreos-base/update-ssh-keys/update-ssh-keys-0.3.0-r6.ebuild
  coreos-base/update-ssh-keys/update-ssh-keys-9999.ebuild
  eclass/coreos-cargo.eclass
  profiles/coreos/arm64/package.accept_keywords
Labels: main

#1767 sec-policy/selinux-unconfined: move to ::portage-stable
  sec-policy/selinux-unconfined/Manifest
  sec-policy/selinux-unconfined/metadata.xml
  sec-policy/selinux-unconfined/selinux-unconfined-2.20200818-r2.ebuild
  sec-policy/selinux-unconfined/selinux-unconfined-2.20210203-r1.ebuild
  sec-policy/selinux-unconfined/selinux-unconfined-9999.ebuild
Labels: main

#1775 profiles: delete keywords for gnutls
  profiles/coreos/base/package.accept_keywords
Labels: main

#1785 sys-fs/mdadm: update to 4.2
  changelog/updates/2022-03-31-mdadm-4.2.md
  sys-fs/mdadm/Manifest
  sys-fs/mdadm/README.md
  sys-fs/mdadm/files/mdadm-4.1-assemble-add-support-for-raid0-layouts.patch
  sys-fs/mdadm/files/mdadm-4.1-create-add-support-for-raid0-layouts.patch
  sys-fs/mdadm/files/mdadm-4.2-in_initrd-collision.patch
  sys-fs/mdadm/mdadm-4.2-r1.ebuild
  sys-fs/mdadm/metadata.xml
Labels: main
