Repository flatcar/coreos-overlay, pull requests merged in 2022-08, with the labels that each got.

#2061 coreos-base/init: keep static network configuration
  changelog/bugfixes/2022-07-27-networkd.md
  coreos-base/coreos-init/coreos-init-9999.ebuild
Labels: alpha, stable, beta, main

#2071 sys-kernel/coreos-sources: Regenerate patches
  sys-kernel/coreos-sources/coreos-sources-5.15.58.ebuild
  sys-kernel/coreos-sources/files/5.15/z0001-kbuild-derive-relative-path-for-srctree-from-CURDIR.patch
  sys-kernel/coreos-sources/files/5.15/z0002-tools-objtool-Makefile-Don-t-fail-on-fallthrough-wit.patch
  sys-kernel/coreos-sources/files/5.15/z0003-PCI-hv-Make-the-code-arch-neutral-by-adding-arch-spe.patch
  sys-kernel/coreos-sources/files/5.15/z0004-PCI-hv-Add-arm64-Hyper-V-vPCI-support.patch
  sys-kernel/coreos-sources/files/5.15/z0005-Drivers-hv-vmbus-Propagate-VMbus-coherence-to-each-V.patch
  sys-kernel/coreos-sources/files/5.15/z0006-PCI-hv-Avoid-the-retarget-interrupt-hypercall-in-irq.patch
  sys-kernel/coreos-sources/files/5.15/z0007-PCI-hv-Remove-unused-hv_set_msi_entry_from_desc.patch
Labels: alpha, stable, beta, main, flatcar-3227, flatcar-3277, flatcar-3305

#2069 coreos-base/coreos-init: bump commit ID
  changelog/bugfixes/2022-08-03-cloudinit.md
  changelog/bugfixes/2022-08-03-systemd-networkd.md
  coreos-base/coreos-init/coreos-init-9999.ebuild
Labels: alpha, stable, beta, main

#2078 net-libs/libtirpc: update to 1.3.2-r1
  changelog/security/2022-08-03-libtirpc-CVE-2021-46828.md
  net-libs/libtirpc/README.md
  net-libs/libtirpc/files/libtirpc-1.3.2-dos.patch
  net-libs/libtirpc/files/libtirpc-1.3.2-fix-dos.patch
  net-libs/libtirpc/files/libtirpc-1.3.2-memory-leak.patch
  net-libs/libtirpc/files/libtirpc-1.3.2-use-after-free.patch
  net-libs/libtirpc/libtirpc-1.3.2-r1.ebuild
Labels: main

#2081 profiles: enable dev-vcs/git 2.37.1
  profiles/coreos/base/package.accept_keywords
  profiles/coreos/base/package.unmask
Labels: main

#2082 coreos-base/coreos-init: Add new image signing key to flatcar-install
  changelog/changes/2022-08-11-new-image-signing-subkey.md
  coreos-base/coreos-init/coreos-init-9999.ebuild
Labels: alpha, stable, beta, main

#2110 Flatcar support for EKS on versions above 1.21
  changelog/bugfixes/2022-08-22-eks-support-for-versions-above-1.21.md
  coreos-base/flatcar-eks/files/download-kubelet.sh
Labels: alpha, stable, beta, main

#2111 Toolchain update
  app-torcx/docker/docker-20.10.ebuild
  coreos/config/env/dev-lang/perl
  coreos/config/env/sys-devel/flex
  coreos/config/env/sys-devel/gettext
  coreos/config/env/sys-devel/libtool
  profiles/coreos/arm64/package.use.mask
  profiles/coreos/base/package.accept_keywords
  profiles/coreos/targets/sdk/package.use.mask
  sys-auth/sssd/sssd-2.3.1-r4.ebuild
  sys-devel/make/Manifest
  sys-devel/make/README.md
  sys-devel/make/files/make-3.82-darwin-library_search-dylib.patch
  sys-devel/make/files/make-4.2-default-cxx.patch
  sys-devel/make/files/make-4.3-handle-tmpfile-fail.patch
  sys-devel/make/make-4.3.ebuild
  sys-devel/make/metadata.xml
  sys-libs/glibc/Manifest
  sys-libs/glibc/glibc-2.33-r14.ebuild
  sys-libs/glibc/metadata.xml
Labels: main

#2120 coreos-base/coreos-init: sync commit ID
  changelog/bugfixes/2022-08-29-vmware-wireguard.md
  coreos-base/coreos-init/coreos-init-9999.ebuild
Labels: alpha, stable, beta, main
