Repository flatcar/coreos-overlay, pull requests merged in 2022-07, with the labels that each got.

#2001 preparation for glibc 2.34
  app-admin/adcli/Manifest
  app-admin/adcli/adcli-0.9.0.ebuild
  app-admin/adcli/adcli-9999.ebuild
  app-admin/adcli/metadata.xml
  changelog/updates/2022-06-13-gdb-11.2-update.md
  coreos-base/coreos/coreos-0.0.1-r303.ebuild
  coreos-base/coreos/coreos-0.0.1.ebuild
  profiles/coreos/base/package.accept_keywords
  sys-devel/gdb/Manifest
  sys-devel/gdb/files/gdb-11.2-glibc-2.35-fsqrt.patch
  sys-devel/gdb/files/gdb-9.1-ia64.patch
  sys-devel/gdb/files/gdb-9.2-sim-ppc-fno-common.patch
  sys-devel/gdb/gdb-11.2.ebuild
  sys-devel/gdb/gdb-9.2-r1.ebuild
  sys-devel/gdb/metadata.xml
Labels: main

#2029 profiles: remove outdated arm64 accept_keywords for curl
  profiles/coreos/arm64/package.accept_keywords
Labels: main

#2038 profiles: enable symlink for nmap
  changelog/changes/2022-07-19-ncat.md
  profiles/coreos/base/package.use
Labels: main

#2040 changelog: add missing CVE for Go 1.18.4, 1.17.12
  changelog/security/2022-07-13-go-1.18.4-update.md
Labels: alpha, stable, beta, main

#2057 sys-apps/systemd: fix tmpfile entry for resolv.conf link
  changelog/bugfixes/2022-07-26-restore-resolv-conf.md
  sys-apps/systemd/systemd-250.3-r1.ebuild
  sys-apps/systemd/systemd-250.3.ebuild
Labels: alpha, stable, beta

#2030 app-containers/syft: add v0.51.0 to sdk
  app-containers/syft/Manifest
  app-containers/syft/metadata.xml
  app-containers/syft/syft-0.51.0.ebuild
Labels: main

#2060 sys-apps/ignition: add networkd translate fix
  changelog/bugfixes/2022-07-27-ignition-networkd.md
  sys-apps/ignition/files/0016-mod-bump-ign-converter-to-pull-networkd-fix.patch
  sys-apps/ignition/ignition-2.14.0-r3.ebuild
  sys-apps/ignition/ignition-9999.ebuild
Labels: alpha, stable, beta, main
