Repository flatcar/coreos-overlay, pull requests merged in 2022-04, with the labels that each got.

#1782 sys-libs/zlib: Add arches to package.accept_keywords
  profiles/coreos/base/package.accept_keywords
Labels: main

#1793 app-emulation/open-vmdk: remove Flatcar patch for builds with gcc 10
  app-emulation/open-vmdk/files/vmdk-fix-build-issues-with-gcc-10-or-newer.patch
  app-emulation/open-vmdk/open-vmdk-1.0.ebuild
Labels: main

#1769 coreos-base/afterburn: sync with 5.2.0
  changelog/updates/2022-03-31-afterburn.md
  coreos-base/afterburn/Manifest
  coreos-base/afterburn/afterburn-5.2.0.ebuild
  coreos-base/afterburn/afterburn-9999.ebuild
  coreos-base/afterburn/files/0001-Revert-remove-cl-legacy-feature.patch
  coreos-base/afterburn/files/0002-util-cmdline-Handle-the-cmdline-flags-as-list-of-sup.patch
  coreos-base/afterburn/files/0003-encode-information-for-systemd-networkd-wait-online.patch
  coreos-base/afterburn/files/coreos-metadata-sshkeys@.service
  coreos-base/afterburn/files/coreos-metadata.service
Labels: main

#1801 sys-kernel/coreos-modules: build RAPL module
  changelog/changes/2022-04-08-kernel.md
  sys-kernel/coreos-modules/files/amd64_defconfig-5.15
Labels: main

#1816 profiles: accept keywords ~arm64 for app-arch/libarchive 3.6.1
  profiles/coreos/arm64/package.accept_keywords
Labels: main

#1813 fix GCP OEM functionality
  app-emulation/google-compute-engine/Manifest
  app-emulation/google-compute-engine/google-compute-engine-20190124-r1.ebuild
  changelog/bugfixes/2022-04-12-fix-gcp-oem-service.md
  changelog/updates/2022-04-12-google-compute-engine.md
  coreos-base/oem-gce/files/units/oem-gce.service
  coreos-base/oem-gce/oem-gce-20180823-r3.ebuild
  profiles/coreos/targets/generic/oem-aci/make.defaults
  profiles/coreos/targets/generic/oem-aci/package.provided
Labels: alpha, stable, beta, main, flatcar-3139, flatcar-3185, flatcar-3200

#1802 GCP gVNIC support
  changelog/changes/2022-04-07-google-gve.md
  coreos-base/coreos-init/coreos-init-0.0.1-r175.ebuild
  coreos-base/coreos-init/coreos-init-9999.ebuild
  sys-kernel/coreos-modules/files/amd64_defconfig-5.15
Labels: flatcar-3033, flatcar-3139, flatcar-3185, flatcar-3200

#1839 Add missing pahole dependencies
  changelog/bugfixes/2022-04-25-fix-dev-container-module-builds.md
  coreos-base/coreos-dev/coreos-dev-0.1.0.ebuild
  eclass/coreos-kernel.eclass
  sys-kernel/coreos-sources/coreos-sources-5.15.35.ebuild
Labels: alpha, stable, beta, main, flatcar-3033, flatcar-3139, flatcar-3185, flatcar-3200
