Repository flatcar/coreos-overlay, pull requests merged in 2023-01, with the labels that each got.

#2363 Update sys-apps/systemd to 251.10 and do some cleanups in profiles
  changelog/security/2022-01-09-systemd-update.md
  changelog/updates/2022-01-09-systemd-update.md
  profiles/coreos/base/package.use
  profiles/coreos/targets/generic/package.use
  profiles/features/systemd/package.accept_keywords
  profiles/features/systemd/package.unmask
  profiles/features/systemd/package.use.force
  sys-apps/systemd/CHECKLIST.md
  sys-apps/systemd/Manifest
  sys-apps/systemd/files/00-hostnamed-network-user.conf
  sys-apps/systemd/files/0001-wait-online-set-any-by-default.patch
  sys-apps/systemd/files/0002-networkd-default-to-kernel-IPForwarding-setting.patch
  sys-apps/systemd/files/0003-needs-update-don-t-require-strictly-newer-usr.patch
  sys-apps/systemd/files/0004-core-use-max-for-DefaultTasksMax.patch
  sys-apps/systemd/files/0005-systemd-Disable-SELinux-permissions-checks.patch
  sys-apps/systemd/files/0006-Revert-getty-Pass-tty-to-use-by-agetty-via-stdin.patch
  sys-apps/systemd/files/0006-core-handle-lookup-paths-being-symlinks.patch
  sys-apps/systemd/files/251-gpt-auto-no-cryptsetup.patch
  sys-apps/systemd/files/org.freedesktop.hostname1_no_polkit.conf
  sys-apps/systemd/metadata.xml
  sys-apps/systemd/systemd-251.10.ebuild
Labels: main

#2325 sys-apps/portage: Drop our patches, clean up modifications and move to portage-stable
  profiles/coreos/base/make.defaults
  profiles/coreos/base/package.accept_keywords
  profiles/coreos/base/package.use
  sys-apps/portage/Manifest
  sys-apps/portage/README.md
  sys-apps/portage/files/0001-portage-repository-config.py-add-disabled-attribute-.patch
  sys-apps/portage/files/0002-environment-Filter-EROOT-for-all-EAPIs.patch
  sys-apps/portage/files/0003-depgraph-ensure-slot-rebuilds-happen-in-the-correct-.patch
  sys-apps/portage/files/README.RESCUE
  sys-apps/portage/files/portage-ccache.conf
  sys-apps/portage/metadata.xml
  sys-apps/portage/portage-3.0.28-r2.ebuild
Labels: main

#2374 dev-lang/python-oem: update to 3.9.16
  changelog/updates/2023-01-12-python-oem-3.9.16.md
  dev-lang/python-oem/Manifest
  dev-lang/python-oem/README.md
  dev-lang/python-oem/python-oem-3.9.16.ebuild
Labels: main

#2379 profiles: Do not modify preexisting users
  profiles/coreos/base/profile.bashrc
Labels: main

#2380 coreos: Add patches for gentoolkit, portage-utils and gcc-config
  coreos/user-patches/app-portage/gentoolkit/0001-profile-Default-to-main-repo-name.patch
  coreos/user-patches/app-portage/gentoolkit/README.md
  coreos/user-patches/app-portage/portage-utils/0001-main-Print-the-ignored-parent-line-in-warning.patch
  coreos/user-patches/app-portage/portage-utils/0002-main-Handle-empty-repo-names-in-parent-files.patch
  coreos/user-patches/app-portage/portage-utils/README.md
  coreos/user-patches/sys-devel/gcc-config/0001-gcc-config-Use-relative-paths-for-liblto-and-cc-syml.patch
  coreos/user-patches/sys-devel/gcc-config/README.md
Labels: main

#2387 update sys-apps/shadow to 4.13
  changelog/updates/2023-01-18-shadow-4.13.md
  sys-apps/shadow/Manifest
  sys-apps/shadow/files/shadow-4.13-configure-clang16.patch
  sys-apps/shadow/shadow-4.13-r1.ebuild
Labels: main

#2392 profiles: accept keywords ~arm64 for dev-vcs/git 2.37.5 for flatcar-3446
  profiles/coreos/arm64/package.accept_keywords
Labels: beta, flatcar-3446

#2393 profiles: accept keywords ~arm64 for dev-vcs/git 2.38.3 for main
  profiles/coreos/arm64/package.accept_keywords
Labels: main

#2402 sys-kernel/coreos-sources: Add backport of bugfix for #847 for flatcar-3374
  changelog/bugfixes/2023-01-19-kernel-bug-847.md
  sys-kernel/coreos-sources/coreos-sources-5.15.86.ebuild
  sys-kernel/coreos-sources/files/5.15/z0008-ext4-Fix-deadlock-due-to-mbcache-en.patch
Labels: stable, flatcar-3374

#2247 Profiles changes for qemu update
  coreos-base/hard-host-depends/hard-host-depends-0.0.1-r206.ebuild
  coreos-base/hard-host-depends/hard-host-depends-0.0.1.ebuild
  coreos-devel/board-packages/board-packages-0.0.1-r10.ebuild
  coreos-devel/board-packages/board-packages-0.0.1.ebuild
  coreos-devel/sdk-depends/sdk-depends-0.0.1-r45.ebuild
  coreos-devel/sdk-depends/sdk-depends-0.0.1.ebuild
  profiles/coreos/arm64/package.accept_keywords
  profiles/coreos/base/package.accept_keywords
Labels: main

#2362 Profile and app/shells/bash updates for the weekly update
  app-shells/bash/Manifest
  app-shells/bash/bash-5.1_p16-r2.ebuild
  app-shells/bash/files/bashrc
  app-shells/bash/metadata.xml
  coreos-base/coreos/coreos-0.0.1-r305.ebuild
  coreos-base/coreos/coreos-0.0.1.ebuild
  coreos/user-patches/app-arch/ncompress/0001-Fix-link-creation.patch
  coreos/user-patches/app-arch/ncompress/README.md
  profiles/coreos/amd64/sdk/package.accept_keywords
  profiles/coreos/arm64/package.accept_keywords
  profiles/coreos/base/make.defaults
  profiles/coreos/base/package.accept_keywords
  profiles/coreos/base/package.use
  profiles/coreos/targets/generic/package.use.force
  profiles/coreos/targets/generic/use.force
  profiles/coreos/targets/generic/use.mask
  sys-apps/policycoreutils/policycoreutils-3.1-r3.ebuild
Labels: main

#2415 app-emulation/cri-tools: update to 1.24.2
  app-emulation/cri-tools/Manifest
  app-emulation/cri-tools/cri-tools-1.19.0.ebuild
  app-emulation/cri-tools/cri-tools-1.24.2.ebuild
  app-emulation/cri-tools/metadata.xml
  changelog/updates/2023-01-26-cri-tools-1.24.2.md
Labels: alpha, stable, beta, main, flatcar-3374, flatcar-3493
