Repository flatcar/coreos-overlay, pull requests merged in 2023-02, with the labels that each got.

#2418 app-emulation/cri-tools: build with Go 1.18 for flatcar-3374
  app-emulation/cri-tools/cri-tools-1.24.2.ebuild
Labels: stable, flatcar-3374

#2433 net-firewall/iptables: update to 1.8.8-r5
  changelog/updates/2023-02-03-iptables-1.8.8.md
  net-firewall/iptables/Manifest
  net-firewall/iptables/files/iptables-1.8.8-format-security.patch
  net-firewall/iptables/files/iptables-1.8.8-musl-headers.patch
  net-firewall/iptables/files/iptables-1.8.8-out-of-tree-build.patch
  net-firewall/iptables/files/iptables-1.8.8-uint-musl.patch
  net-firewall/iptables/files/iptables-r3.init
  net-firewall/iptables/iptables-1.8.8-r5.ebuild
  net-firewall/iptables/metadata.xml
Labels: main

#2426 app-admin/sudo: update to 1.9.12_p2
  app-admin/sudo/Manifest
  app-admin/sudo/sudo-1.9.12_p2.ebuild
  changelog/security/2023-02-02-sudo-1.9.12_p2.md
  changelog/updates/2023-02-02-sudo-1.9.12_p2.md
Labels: main

#2404 Profile changes and cleanups for weekly updates
  coreos-base/update_engine/update_engine-0.4.10-r10.ebuild
  coreos-base/update_engine/update_engine-9999.ebuild
  coreos/user-patches/app-arch/ncompress/0001-Fix-link-creation.patch
  coreos/user-patches/app-arch/ncompress/README.md
  coreos/user-patches/sys-devel/gcc/0001-constexpr.patch
  coreos/user-patches/sys-devel/gcc/README.md
  profiles/coreos/arm64/package.accept_keywords
  profiles/coreos/base/package.accept_keywords
  profiles/coreos/base/package.mask
  profiles/coreos/base/package.use
Labels: main

#2425 sys-apps/systemd: Update to 252.5
  changelog/updates/2023-02-09-systemd-update.md
  coreos-base/coreos-init/coreos-init-0.0.1-r179.ebuild
  coreos-base/coreos-init/coreos-init-9999.ebuild
  sys-apps/baselayout/baselayout-3.6.8-r8.ebuild
  sys-apps/baselayout/baselayout-9999.ebuild
  sys-apps/systemd/Manifest
  sys-apps/systemd/files/0001-wait-online-set-any-by-default.patch
  sys-apps/systemd/files/0002-networkd-default-to-kernel-IPForwarding-setting.patch
  sys-apps/systemd/files/0003-needs-update-don-t-require-strictly-newer-usr.patch
  sys-apps/systemd/files/0004-core-use-max-for-DefaultTasksMax.patch
  sys-apps/systemd/files/0005-systemd-Disable-SELinux-permissions-checks.patch
  sys-apps/systemd/files/0006-Revert-getty-Pass-tty-to-use-by-agetty-via-stdin.patch
  sys-apps/systemd/files/0007-units-Keep-using-old-journal-file-format.patch
  sys-apps/systemd/files/251-gpt-auto-no-cryptsetup.patch
  sys-apps/systemd/files/252-no-stack-protector-bpf.patch
  sys-apps/systemd/systemd-252.5.ebuild
Labels: main

#2441 .github: fix URL of docker release notes
  .github/workflows/docker-apply-patch.sh
Labels: github-actions

#2435 dev-libs/openssl: update to 3.0.8
  changelog/security/2023-02-08-openssl-3.0.8.md
  changelog/updates/2023-02-08-openssl-3.0.8.md
  dev-libs/openssl/Manifest
  dev-libs/openssl/files/gentoo.config-1.0.4
  dev-libs/openssl/openssl-3.0.8.ebuild
Labels: main

#2460 net-misc/openssh: update to 9.2_p1-r2
  changelog/security/2023-02-14-openssh-9.2.md
  changelog/updates/2023-02-14-openssh-9.2.md
  net-misc/openssh/Manifest
  net-misc/openssh/files/openssh-8.5_p1-hpn-15.2-sctp-glue.patch
  net-misc/openssh/files/openssh-8.6_p1-hpn-version.patch
  net-misc/openssh/files/openssh-9.0_p1-X509-glue-13.4.1.patch
  net-misc/openssh/files/openssh-9.0_p1-X509-uninitialized-delay.patch
  net-misc/openssh/files/openssh-9.1_p1-build-tests.patch
  net-misc/openssh/files/sshd.service.1
  net-misc/openssh/files/sshd_at.service.1
  net-misc/openssh/metadata.xml
  net-misc/openssh/openssh-9.2_p1-r2.ebuild
Labels: main

#2454 profiles: update sys-devel/gcc to 11.3.1_p20230120-r1
  profiles/coreos/arm64/package.accept_keywords
  profiles/coreos/base/package.mask
Labels: main

#2461 Update python to 3.10.x
  app-emulation/wa-linux-agent/wa-linux-agent-2.6.0.2-r1.ebuild
  changelog/updates/2023-02-17-python-update.md
  coreos-base/hard-host-depends/hard-host-depends-0.0.1-r207.ebuild
  coreos-base/hard-host-depends/hard-host-depends-0.0.1.ebuild
  coreos-devel/sdk-depends/sdk-depends-0.0.1.ebuild
  coreos/config/env/dev-lang/python-oem
  dev-lang/python-oem/Manifest
  dev-lang/python-oem/README.md
  dev-lang/python-oem/python-oem-3.10.9-r1.ebuild
  dev-python/boto/Manifest
  dev-python/boto/boto-2.49.0-r4.ebuild
  dev-python/boto/files/boto-2.49.0-py3-httplib-strict.patch
  dev-python/boto/files/boto-2.49.0-py3-server-port.patch
  dev-python/boto/files/boto-2.49.0-py3-socket-binary.patch
  dev-python/boto/files/boto-2.49.0-py310.patch
  dev-python/boto/files/boto-2.49.0-py38.patch
  dev-python/boto/files/boto-2.49.0-try-to-add-SNI-support-v3.patch
  dev-python/boto/files/boto-2.49.0-unbundle-six.patch
  dev-python/boto/metadata.xml
  dev-python/distro-oem/distro-oem-1.7.0-r1.ebuild
  profiles/coreos/arm64/package.accept_keywords
  profiles/coreos/base/make.defaults
  profiles/coreos/base/package.mask
  profiles/coreos/base/package.use.mask
  profiles/coreos/base/use.mask
  profiles/coreos/targets/generic/package.use
  sys-boot/grub/grub-2.02-r9.ebuild
  sys-boot/grub/grub-9999.ebuild
  sys-fs/btrfs-progs/Manifest
  sys-fs/btrfs-progs/README.md
  sys-fs/btrfs-progs/btrfs-progs-6.0.2.ebuild
Labels: main

#2463 Disable CET on 3510
  profiles/coreos/base/use.mask
Labels: alpha

#2466 coreos-base/coreos-init: Exclude K8s' special interfaces
  changelog/bugfixes/2023-02-20-preserve-kubernetes-interfaces.md
  coreos-base/coreos-init/coreos-init-9999.ebuild
Labels: main

#2468 app-emulation/containerd: default to Go 1.19
  app-emulation/containerd/containerd-9999.ebuild
Labels: main

#2469 coreos-base/coreos-init: Fix dummy dev default networkd unit exclusion
  coreos-base/coreos-init/coreos-init-9999.ebuild
Labels: main

#2462 Disable CET on 3493
  profiles/coreos/base/use.mask
Labels: beta

#2471 profiles: accept keyword ~arm64 for net-dns/dnsmasq 2.89
  profiles/coreos/arm64/package.accept_keywords
Labels: main

#2473 app-arch/torcx: update golang.org/x/text to 0.3.8
  app-arch/torcx/torcx-0.2.0-r8.ebuild
  app-arch/torcx/torcx-9999.ebuild
  changelog/security/2023-02-23-torcx-golang-text.md
Labels: main
